containerd/runwasi

.github/workflows/release.yml
- build a release when tag is pushed matching 'v[0-9]+.[0-9]+.*'
Note: only for Linux amd64.
=> add release automation when branch is tagged

.github/workflows/release.yml
forgot to add tag to the release artifact.
=> fix the tag on the release artifact

Cargo.lock, crates/containerd-shim-wasmtime-v1/src/sandbox/instance.rs, crates/containerd-shim-wasmtime-v1/src/sandbox/shim.rs
This allows the instance type to dictate the config of the wasmtime
engine.
=> Add trait to get a wasmtime engine config

Makefile, docs/windows-getting-started.md
=> Adding Windows Getting Started doc

src/instance.rs
Signed-off-by: utam0k <k0ma@utam0k.jp>
Make it read easier.
=> Use the spec builder instead of the json string

crates/containerd-shim-wasm/src/sandbox/cgroups/cgroupv2.rs
Some dists, like [linuxkit](https://github.com/linuxkit/linuxkit/blob/500fdb163ba4921cdb46ebf6b419fa6898fbeac3/kernel/config-5.15.x-x86_64#L799) for example don't have `CONFIG_BLK_CGROUP_IOCOST` activated so writing to `io.weight` fails with a `permission denied` error.
This change brings the implementation in line with what [runc does](https://github.com/opencontainers/runc/blob/81044ad7c902f3fc153cb8ffadaf4da62855193f/libcontainer/cgroups/fs2/io.go#L57-L69).
=> Use io.bfq.weight if available, fallback to io.weight

README.md
Update Instance trait to match the code reality.
=> Update README.md API Instance definition.

crates/containerd-shim-wasm/src/sandbox/shim.rs
Replaced a few `unwrap()` calls with "proper" error handling to stay similar to the style in the rest of the file. It could be that some of the errors can not be ever triggered in practice though.
=> shim: better error handling.

crates/wasmedge/Cargo.toml, crates/wasmedge/src/instance.rs
Test for WasmEdge error exit codes.
=> wasmedge: test for exit with a trap.

crates/containerd-shim-wasm/src/sandbox/shim.rs
This code is only valid for linux, so only compile it there.
=> Make namespace setup conditional on OS

.github/dependabot.yml, Cargo.lock
Add a simple `dependabot.yml` file. Also run `cargo update`.
=> Add dependabot for dependency version checks

crates/containerd-shim-wasmedge/src/instance.rs
Since we are using the `std{in|out|err}` from containerd as raw file descriptors, we need to close them after we pass them to the container process.
=> wasmedge: do not leak stdio file descriptors

.github/workflows/ci.yml, Makefile, README.md
Updates the docs to be clear about dependecies and streamlines a few files so there is concistency with make file.
=> Update the docs to include install deps

crates/oci-tar-builder/README.md, crates/oci-tar-builder/src/bin.rs
Follow up based on some feedback provided in original PR: https://github.com/containerd/runwasi/pull/135#pullrequestreview-1476803407
/assign @ipuustin
=> Improve OCI Artifact binary based on feedback

crates/containerd-shim-wasmedge/src/instance.rs, crates/containerd-shim-wasmtime/src/instance.rs
This is some cleanup for functions that are only used in the tests for the shims.
=> Move code that is only used in the tests

crates/containerd-shim-wasm/src/sandbox/manager.rs, crates/containerd-shim-wasm/src/sandbox/oci.rs, crates/containerd-shim-wasm/src/sandbox/shim.rs
=> remove `load` and `spec_from_file` from oci

Cargo.lock, Cargo.toml
This will unblock some PRs like #268 and #254
=> Bump Containerd shim to 0.5.0

Cargo.lock, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasm/src/sys/unix/metrics.rs
=> refactor: use collect_metrics

.github/workflows/action-test-k3s.yml, .github/workflows/ci.yml, Cargo.lock, Cargo.toml, Makefile, crates/containerd-shim-wasmer/Cargo.toml, crates/containerd-shim-wasmer/src/bin/containerd-shim-wasmer-v1/main.rs, crates/containerd-shim-wasmer/src/bin/containerd-shim-wasmerd-v1/main.rs, crates/containerd-shim-wasmer/src/bin/containerd-wasmerd/main.rs, crates/containerd-shim-wasmer/src/executor.rs, crates/containerd-shim-wasmer/src/instance/instance_linux.rs, crates/containerd-shim-wasmer/src/instance/instance_windows.rs, crates/containerd-shim-wasmer/src/lib.rs
Add support for wasmer.
Fix #275
=> add wasmer

.github/workflows/action-build.yml, .github/workflows/action-fmt.yml, .github/workflows/ci.yml, Makefile
=> Fix `Makefile` to avoid duplicated work in CI

README.md
=> add wasmer doc

.github/workflows/release.yml
=> Use makefile and timeout in release workflow

crates/containerd-shim-wasm/src/sandbox/shim.rs
Hi all,
Together with @DMajrekar and @saiyam1814 I've tried to run the runwasi based shims on Talos Linux. It failed because the shims tried to write to a read-only folder. As described in #325.
During testing I removed the code that caused the problem as done in this PR and I expected mounts like `/etc/hosts` and `/var/run/secrets/kubernetes.io/serviceaccount/token` to be missing but they are still there. I assume it is handled by libcontainer.
So my idea was to exclude this code when libcontainer is used, but it seems that libcontainer is always used when the platform is unix.
```rust
[target.'cfg(unix)'.dependencies].
libcontainer = { workspace = true, features = ["libseccomp", "systemd", "v1", "v2"]}
...
```
This leads me to the question of whether the code is needed at all. …
=> fix: avoid writing to read-only fs on talos

Cargo.lock, crates/containerd-shim-wasmtime/Cargo.toml, crates/containerd-shim-wasmtime/src/instance.rs
=> chore(wasmtime): bump wasmtime to v14

MAINTAINERS
Based on the significant contributions to this project, I would like to propose we promote @jprendes to committer.
=> Promote @jprendes to committer

Cargo.lock, Cargo.toml, crates/containerd-shim-wasm/Cargo.toml
* `containerd-wasm-shim` 0.4.0 -> 0.5.0
* other crates 0.3.1 -> 0.4.0
=> chore(*): bump crates version

Cargo.lock, Cargo.toml
Update containerd-shim to 0.7.0
=> Update containerd-shim to 0.7.0

.github/workflows/release.yml
=> Add a user to git commit

.github/workflows/release.yml
The main branch is protected so we cannot do commits to it
=> Remove auto-commit and verify version

.github/workflows/release.yml
=> ci(release): remove pre-release

.github/workflows/release.yml
fix a regression introduced by #548
=> fix(release): syntax error in runtime_sub step

.github/workflows/release.yml
well, it turns out that #603 does not fix the whole issue. This PR is an attempt to address it.
=> fix(release): fix another syntax error on runtime_sub

.github/dependabot.yml
This commit groups patch updates to reduce # of dependabot PRs.
Inspired by https://github.com/containers/youki/pull/2496
=> feat(dependabot): group patch updates to eliminate PRs

crates/containerd-shim-wasm/src/sandbox/shim/local.rs
this commit splits the long-running wait function and exports child spans every 60 seconds.
Example:
Note: in the example, I changed the interval time to 2s instead of 60s.
=> feat(otel): split long-running wait function to child spans

Cargo.lock, benches/containerd-shim-benchmarks/Cargo.toml, crates/containerd-shim-wasm-test-modules/Cargo.toml, crates/containerd-shim-wasmedge/Cargo.toml, crates/containerd-shim-wasmer/Cargo.toml, crates/containerd-shim-wasmtime/Cargo.toml
remove unused deps in youki, found by running `cargo machete`
=> Cargo: remove unused deps 

.github/workflows/ci.yml
this allows us to review dependencies for known vulnerabilities
=> .github/workflows/ci: add a dependency review job

Cargo.lock, Cargo.toml, crates/containerd-shim-wasmtime/src/instance.rs
=> Upgrade wasmtime to version 25.0.1

RELEASE.md
- Removed outdated crate release sequence related to test modules.
- Reorganized and clarified release process steps.
=> RELEASE: Refactor release documentation

README.md, crates/containerd-shim-wasm/src/container/engine.rs
Match the description of can_handle in README with the actual code.
https://github.com/containerd/runwasi/blob/251575a68dd334c8de936e15c2b704634009d254/crates/containerd-shim-wasm/src/container/engine.rs#L21
=> Fix description of can_handle

Cargo.lock, Cargo.toml, crates/containerd-shim-wamr/Cargo.toml, crates/containerd-shim-wasm/Cargo.toml
* bump containerd-shim-wasm to v0.8.0
* changed the warm crate version to v0.1.0
=> release: bump up the containerd-shim-wasm crate version to v0.8.0

.github/workflows/action-sign.yml
add the missing checkout action to the action-sign
=> release: add the missing checkout in action-sign

crates/containerd-shim-wasmtime/src/instance.rs
=> Set memory maximum size when checking pool allocation

docs/opentelemetry.md
=> docs/opentelemetry: update the APIs to reflect the latest changes

Cargo.lock, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasm/src/sandbox/shim/otel.rs
=> revert f38990d that resulted in no traces being exported to Jeager

.github/labeler.yml, .github/workflows/labeler.yml
Inspired by https://github.com/containerd/rust-extensions/commit/8e4a27009bb8b50ee1474782c832fcb546c137ff
=> feat(ci): Automatically assign labels to PRs

crates/containerd-shim-wasm/src/sandbox/shim/otel.rs, scripts/verify-jaeger-traces.sh
- Modify the span name from funcion name to the module path + function name
=> feat(otel): modify the span naming logic

crates/containerd-shim-wasm/src/sandbox/shim/local/tests.rs
Tests for https://github.com/containerd/runwasi/pull/864
=> feat: add tests of runtime options

Makefile, README.md, test/k3s/bootstrap.sh
fix: https://github.com/containerd/runwasi/issues/889
=> Support for k3s using containerd 2.0

.github/workflows/action-build.yml, .github/workflows/action-check.yml, .github/workflows/action-test-image.yml, .github/workflows/action-test-k3s.yml, .github/workflows/action-test-kind.yml, .github/workflows/action-test-smoke.yml, .github/workflows/benchmarks.yml, .github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/release-wasi-demo-app.yml, .github/workflows/release.yml, .github/workflows/sbom.yml, .github/workflows/sign.yml
Reverts containerd/runwasi#911
=> Revert "ci(all): add read-all permission to all workflows"

docs/src/resources/troubleshooting.md
- Add guidence for container startup failures
- Add log-based troubleshooting guide
=> docs: Add troubleshooting guide for runwasi shims

docs/src/developer/architecture.md
=> docs: update architecture doc to introduce the `containerd-shimkit` crate

crates/containerd-shim-wasm/CHANGELOG.md
=> containerd-shim-wasm/changelog: tidy up

.github/workflows/release.yml, Makefile
- **add shimkit to non_shim_crates list**
- **add build, check and test targets for shimkit**
Trying to fix this release pipeline failure: https://github.com/containerd/runwasi/actions/runs/14088763087/job/39459775210
=> fix release pipeline shimkit

crates/containerd-shimkit/CHANGELOG.md
=> shimkit: Update CHANGELOG.md for v0.1.0 release

Cargo.lock, Cargo.toml, crates/containerd-shim-wasm/CHANGELOG.md, crates/containerd-shim-wasm/Cargo.toml
=> containerd-shim-wasm: bump version to 1.0.0 and updated CHANGELOG

crates/containerd-shimkit/src/sandbox/cli.rs, crates/containerd-shimkit/src/sandbox/shim/local.rs, crates/containerd-shimkit/src/sys/windows/metrics.rs
We have some clippy warning on Windows, this fixes them.
=> [chore] Fix clippy on Windows

Cargo.lock, Cargo.toml, crates/containerd-shim-wasm/CHANGELOG.md, crates/containerd-shim-wasm/Cargo.toml
=> containerd-shim-wasm: bump version to 1.0.0-rc.1

Cargo.lock, Cargo.toml, crates/containerd-shim-wasm/Cargo.toml
=> containerd-shim-wasm: bump version to 1.0.0

Cargo.lock, crates/containerd-shim-wamr/Cargo.toml, crates/containerd-shim-wasmedge/Cargo.toml, crates/containerd-shim-wasmer/Cargo.toml, crates/containerd-shim-wasmtime/Cargo.toml
=> chore: batch bump minor version of shim binaries

docs/src/getting-started/installation.md
fix: https://github.com/containerd/runwasi/issues/989
=> docs: fix installation guide to pull the test image
