containerd/runwasi

.github/workflows/release.yml
The RUNNER_OS env var was not set in the release job, so it made the release artifact name look like it has an extra "-". This adds the env var.
This var will likely be useful in the future when building for multiple architectures / OSes.
=> add the runner os release env var

.github/workflows/ci.yml, .github/workflows/release.yml
v2 is deprecated, so move to v3
=> Update actions versions

crates/containerd-shim-wasm/src/sandbox/cgroups/cgroupv2.rs, crates/containerd-shim-wasm/src/sandbox/cgroups/mod.rs
The test for nested cgroups was failing for v2 cgroups because controllers have to be explicitly enabled for child cgroups.
This change makes sure we enable those controllers for all parents of a nested cgroup *that we are creating*.
This does not change parents that we did not create.
Fixes #28
=> cgroups: v2: Enable all controllers from parent

crates/containerd-shim-wasm/src/sandbox/testutil.rs
Cargo seems to really enjoy messing with the tty.
Instead of having 2 cargos (main one that executed the test originally, then the sub-test runner) access to the same terminal, make the subprocess go through a pipe for stdout and stderr.
=> Fix issue with sudo test runner messing with tty

crates/containerd-shim-wasm/src/sandbox/cgroups/cgroupv2.rs, crates/containerd-shim-wasm/src/sandbox/exec.rs
A cgroup can either have delegations (`cgroup.subtree_control` is populated) OR it can have processes in it, but not both. So we need to make sure that we don't add any controllers to the new cgroup's `cgroup.subtree_control` BUT we should continue to do so for any parents that we create.
Fixes #35
=> cgroup: v2: do not set subtree_control for new cg

Cargo.lock, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasm/src/sandbox/cgroups/cgroupv1.rs, crates/containerd-shim-wasm/src/sandbox/cgroups/cgroupv2.rs, crates/containerd-shim-wasm/src/sandbox/cgroups/mod.rs, crates/containerd-shim-wasm/src/sandbox/exec.rs
This allows tests to fully cleanup.
`Drop` is only implemented for this wrapper because we usually don't
want to delete cgroups just because the value went out of scope.
The test wrapper also deletes all parents to make sure the full tree is
deleted.
=> Add a cgroup wrapper which implements Drop

.dockerignore, .github/workflows/ci.yml, .gitignore, Makefile, crates/containerd-shim-wasm/src/sandbox/cgroups/cgroupv2.rs, test/k8s/Dockerfile, test/k8s/deploy.yaml
See individual commits for descriptions.
=> Add tests for k8s and fix cgroup issue

crates/containerd-shim-wasm/src/sandbox/cgroups/cgroupv2.rs
Some runtimes will send 0 for these values, make sure we don't panic with an `thread 'main' panicked at 'attempt to subtract with overflow'` error
=> Make sure cpu shares and blkio weight doesn't overlow

crates/wasmedge/src/instance.rs, crates/wasmtime/src/instance.rs
It looks like the `drop(lock)` operation is a no-op, since `lock` is a reference. Looking at the code, I think the idea is that the MutexGuard would be dropped, so I changed the implementation to that. @cpuguy83 can you confirm? Also drop one drop from tests, where the "dropped" value derives Copy.
=> Fix drop() calls.

crates/containerd-shim-wasm/src/sandbox/cgroups/cgroupv1.rs, crates/containerd-shim-wasm/src/sandbox/cgroups/cgroupv2.rs, crates/containerd-shim-wasm/src/sandbox/cgroups/mod.rs, crates/containerd-shim-wasm/src/sandbox/error.rs, crates/containerd-shim-wasm/src/sandbox/exec.rs, crates/containerd-shim-wasm/src/sandbox/oci.rs, crates/containerd-shim-wasm/src/sandbox/shim.rs, crates/oci-tar-builder/src/lib.rs, crates/wasi-demo-app/src/main.rs, crates/wasmedge/src/instance.rs, crates/wasmedge/src/oci_utils.rs, crates/wasmtime/src/instance.rs
I ran clippy static code analysis, and the tool had a bunch of suggestions. Some of the fixes make a lot of sense but some are mostly style issues. I split the fixes to a number of commits, so if need be, I can easily remove some fix classes where the benefit might not be clear.
One thing that came up is that there is a lot of code duplication between wasmtime and wasmedge crates. I'm thinking a utility library would be useful for sharing code. This way the possible bugs would be just in one place. :-)
=> Cleanups from static code analysis

crates/containerd-shim-wasm/src/sandbox/shim.rs, crates/wasmedge/src/instance.rs, crates/wasmtime/src/instance.rs
Moving this makes pre-start hooks work for all the instances.
=> Move call of the prestart hooks over to the lib part

Cargo.lock, Cargo.toml, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasm/src/sandbox/oci.rs, crates/oci-tar-builder/Cargo.toml, crates/thirdparty/Cargo.toml, crates/wasi-demo-app/Cargo.toml, crates/wasmedge/Cargo.toml, crates/wasmtime/Cargo.toml
This PR also modifies `use cap_std::path::PathBuf` to `std::fs::PathBuf` since it's removed from `cap_std` since `0.25`.
Signed-off-by: jiaxiao zhou <jiazho@microsoft.com>
=> Inherit workspace's dependencies and other metadata

Makefile
k3s is newbee friendly and production available. To avoid polluting the system, the binaries of k3s and wasmedge are downloaded to the bin folder, and k3s service renamed to k3s-runwasi.
Since k3s only support linux, this test can only run in linux platform. For macos platform [multipass](https://multipass.run/) or [lima](https://github.com/lima-vm/lima) needed. For windows platform wsl2 needed.
=> feat: add k3s test

Cargo.lock, Cargo.toml, crates/thirdparty/Cargo.toml
Updates nix and oci-spec dependencies by makeing the thrid party crate use the same dep as rest of the workspace.
=> Update nix and oci-spec dependencies

.github/workflows/ci.yml, .github/workflows/release.yml
This PR is a temporary fix for the CI and release workflows which removes build artifact caching to unblock PRs. There should be a follow up PR which determines a better way to cache build artifacts such that if an underlying native lib dependency no long exists on the runner, the cache would pop. 
closes #76.
=> remove ci and release cachine due to cached artifact poisoning

crates/containerd-shim-wasm/src/sandbox/oci.rs
I guess I found an unnecessary method
=> chore: remove unnecessary method

.github/workflows/release.yml, RELEASE.md, scripts/bins.jq, scripts/bins.sh, scripts/crates.jq, scripts/version.sh
Example successful run: https://github.com/cpuguy83/runwasi-fork/actions/runs/4347852402'
crates.io package: https://crates.io/crates/containerd-shim-wasm/versions
Note I yanked the version because it is technically incorrect since I did not set the version in Cargo.toml.
And here is a run where I added validation to ensure the Cargo.toml version matches the tag: https://github.com/cpuguy83/runwasi-fork/actions/runs/4348574593
To support this without having to create an API token from my personal account, I setup a bot account @containerd-runwasi-release-bot which has 2FA enabled.
Additionally once the crates.io package was created I manually set the owners of the package:
This will need to be done for the first release on crates.io for each new crate.
Also just to note, …
=> Add cargo publish step to release pipeline

crates/containerd-shim-wasm/Cargo.toml
Sets containerd-shim-wasm crate's version so it can be tagged and published to crates.io
=> Release containerd-shim-wasm v0.1.0

.github/workflows/ci.yml, Cargo.lock, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasm/README.md, crates/containerd-shim-wasm/build.rs, crates/containerd-shim-wasm/doc/doc.md, crates/containerd-shim-wasm/doc/header.md, crates/containerd-shim-wasm/src/lib.rs, crates/containerd-shim-wasm/src/sandbox/cgroups/cgroupv1.rs, crates/containerd-shim-wasm/src/sandbox/cgroups/cgroupv2.rs, crates/containerd-shim-wasm/src/sandbox/cgroups/mod.rs, crates/containerd-shim-wasm/src/sandbox/error.rs, crates/containerd-shim-wasm/src/sandbox/exec.rs, crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasm/src/sandbox/manager.rs, crates/containerd-shim-wasm/src/sandbox/mod.rs, crates/containerd-shim-wasm/src/sandbox/oci.rs, crates/containerd-shim-wasm/src/sandbox/shim.rs, crates/containerd-shim-wasm/src/sandbox/testutil.rs, crates/containerd-shim-wasm/src/services.rs, scripts/validate-docs.sh
1. Docs were using godoc style docs rather than rustdoc, so were not being picked up by rustdoc
2. Added some missing docs
3. Gave containerd-shim-wasm crate its own README.md so it makes more sense on crates.io
Example rustdoc:
=> Fix code docs

Cargo.lock, Cargo.toml, crates/containerd-shim-wasmtime/Cargo.toml, crates/containerd-shim-wasmtime/src/error.rs
Because there is a shared dep (wasmtime-fiber) between the wasmtime shim and the wasmedge shim, and that dep links to native code, these normally have to be updated in sync, but wasmtime-fiber is a transitive dependency in wasmedge and requires updating upstream before we can do anything here, which is not ideal, especially going forward. We could split the shims out of the workspace... but then that's almost as painful to deal with given all the other shared dependencies.
For now this changes the wasmtime shim to disable the `async` feature which makes means wasmtime-fiber is no longer a dependency in the wasmtime shim.
We also don't use any async functions so this shouldn't really be changing anything.
=> Bump wasmtime to 6.0

MAINTAINERS
I'd like to invite @rumpl as a **reviewer**. He had made sustained commits to runwasi, demonstrated his technical depth and had enough background context and knowledge on this project. 
Needs explicit LGTM from @rumpl and 1/3 of the runwasi Committers according to https://github.com/containerd/project/blob/main/GOVERNANCE.md. 
This PR will remain open for 7 days.
=> MAINTAINERS: Add Djordje Lukic(rumpl) as a REVIEWER

MAINTAINERS
I'd like to invite @ipuustin as a **reviewer**. He had made many contributions to this project since the begining of this year and demonstrated his deep knowledge in this field.
Needs explicit LGTM from @ipuustin and 1/3 of the runwasi Committers according to https://github.com/containerd/project/blob/main/GOVERNANCE.md.
This PR will remain open for 7 days.
=> MAINTAINERS: Add Ismo Puustinen(ipuustin) as a REVIEWER

.github/workflows/ci.yml, .gitmodules, Cargo.lock, Cargo.toml, Dockerfile, README.md, crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasm/src/sandbox/mod.rs, crates/containerd-shim-wasm/src/sandbox/shim.rs, crates/containerd-shim-wasm/src/sandbox/testutil.rs, crates/containerd-shim-wasmedge/Cargo.toml, crates/containerd-shim-wasmedge/src/executor.rs, crates/containerd-shim-wasmedge/src/instance.rs, crates/containerd-shim-wasmedge/src/lib.rs, crates/containerd-shim-wasmtime/src/instance.rs, test/k8s/Dockerfile
Partially Fix: https://github.com/containerd/runwasi/issues/23 (After this PR, I'm planning to create a PR to address wasmtime.)
Remaining issues
=> runwasi: Use youki to fully support OCI runtime spec in wasmedge

crates/containerd-shim-wasmtime/src/instance.rs
This enables someone to pass `/main.wasm#foo` as the `arg[0]` and for it to call a specific method in that WASM file instead of assuming that `_start` is the only entrypoint.
=> Add the ability to call specific modules in wasmtime.

crates/containerd-shim-wasm/src/sandbox/testutil.rs
Noticed that when we use `run_test_with_sudo` from wasmedge shim (such as in https://github.com/containerd/runwasi/pull/78), the test name passed to the function contains `::{{closure}}` at the end, meaning that the tests aren't triggered by the test runner. The name normalization fixes it. I'm thinking we might at some point add more checks and validation, so I made a separate function.
=> testutil: normalize test names.

Makefile
These targets fail to compile in release mode. Any build command should contain `$(RELEASE_FLAG)`.
=> Missing release flag option for some targets.

README.md, crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasm/src/sandbox/shim.rs, crates/containerd-shim-wasmedge/src/instance.rs, crates/containerd-shim-wasmtime/src/instance.rs
The idea is that the shim implementations would need to do less thread management.
Fixes: #67 
@cpuguy83 would this approach make sense? It should maybe be part of a wider API change if it is needed.
=> Redo wait() API.

Cargo.toml
Disable `chrono` crate default features. This is because of a [potential vulnerability](https://rustsec.org/advisories/RUSTSEC-2020-0071) in `time` crate, which is a `chrono` dependency. Runwasi shims in this repository don't appear to be affected by the vulnerability since we don't set environmental variables.
=> deps: do not use chrono default features.

.github/workflows/ci.yml, .github/workflows/release.yml, Cargo.lock, Dockerfile, Makefile, README.md, crates/containerd-shim-wasmedge/Cargo.toml, crates/containerd-shim-wasmedge/src/executor.rs, crates/containerd-shim-wasmedge/src/instance.rs, test/k8s/Dockerfile
1. bump new version
2. remove async feature relative to #72
> According to the information I received from my colleague, there is no urgent need for a fork at the moment, so let me disable it here first.
=> chore: bump wasmedge to 0.12.1 and wasmedge-sdk to 0.8.1

.github/dependabot.yml, Cargo.lock, crates/containerd-shim-wasmtime/Cargo.toml
This supercedes #122 
This PR also adds "wasmtime", "wasi-common" and "wasmtime-wasi" deps to be ignored by the dependabot because it is usually required to update all together, but dependabot has tried to update individual dep which failed the pipelines.
=> Bump wasmtime to 9.0.2

crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasmedge/src/instance.rs, crates/containerd-shim-wasmtime/src/instance.rs
Add `delete()` to Wasmtime tests. Also clean up the code a little to make `cargo clippy` succeed.
=> Fixes to tests to make cargo clippy succeed

Cargo.lock, Makefile, crates/oci-tar-builder/Cargo.toml, crates/oci-tar-builder/README.md, crates/oci-tar-builder/src/bin.rs, crates/oci-tar-builder/src/lib.rs
Address #108 
This adds an experimental tool for creating a WASM OCI Artifacts based on the proposal in https://docs.google.com/document/d/11shgC3l6gplBjWF1VJCWvN_9do51otscAm0hBDGSSAc.  Containerd and runwasi don't currently support the OCI artifact format that is generated.
=> Add support for building Containerd OCI Artifacts

.gitmodules, Cargo.lock, Cargo.toml, benches/containerd-shim-benchmarks/Cargo.toml, benches/containerd-shim-benchmarks/benches/webassembly-benchmarks.rs
Add a submodule "webassembly-benchmarks". The benchmark contains a set of wasm files from libsodium. Only the benchmarks which are fast to run (take under 5 seconds to complete on a desktop computer using WasmEdge) were selected for benchmarking.
The benchmark suite initializes the Wasm runtime, runs the benchmark, and cleans up the container. This is done for both WasmEdge and Wasmtime shim crates. Note that the results for the two runtimes shouldn't really be directly compared right now, because Wasmtime shim hasn't been converted to youki/libcontainer-rs yet and that changes the performance due to the extended namespacing. What this helps with is to see what is the performance impact of any given change, for example having the Youki integration done, using a seccomp filter, or setting …
=> benchmarks: add initial benchmarking support.

crates/containerd-shim-wasmedge/src/instance.rs
This PR removes an extra space that causes the default container root dir to not be a valid / absolute path.
=> fix: remove an extra space in default container root dir

Cargo.lock, Cargo.toml, crates/containerd-shim-wasmedge/src/executor.rs, crates/containerd-shim-wasmedge/src/instance.rs
Since youki now uses thiserror instead of anyhow, this PR also updates the containerd-shim-wasmedge to properly map the error.
=> Update youki to the latest main branch and oci-spec to 0.6.1.

MAINTAINERS
I'd like to invite @utam0k as a reviewer. He had made major contribution to the integration of the WasmEdge shim with youki's `libcontainer` crate and demonstrated his deep knowledge in this field.
Needs explicit LGTM from @utam0k and 1/3 of the runwasi Committers according to https://github.com/containerd/project/blob/main/GOVERNANCE.md.
This PR will remain open for 7 days.
=> MAINTAINERS: Add Toru Komatsu(utam0k) as a REVIEWER

Cargo.lock, crates/containerd-shim-wasmtime/Cargo.toml
This commits bumps the `wasmtime` dep to 10.0.
=> chore: bumps the wasmtime dep to 10.0 in wasmtime shim

Cargo.lock, Cargo.toml
This commit bumps youki libcontainer crate to newly released v0.1.0
=> chore: bump libcontainer to v0.1.0

crates/oci-tar-builder/src/bin.rs
When specifying an uncreated output directory, the command will fail
```sh
cargo run --bin oci-tar-builder -- --name wasi-demo-app --repo localhost:5000 --module ./target/wasm32-wasi/debug/wasi-demo-app.wasm -o ./bin                                                          130 ↵
Compiling oci-tar-builder v0.1.0 (/Users/icebergu/workspace/wasm/runwasi/crates/oci-tar-builder)
Finished dev [unoptimized + debuginfo] target(s) in 1.48s
Running `target/debug/oci-tar-builder --name wasi-demo-app --repo 'localhost:5000' --module ./target/wasm32-wasi/debug/wasi-demo-app.wasm -o ./bin`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/oci-tar-builder/src/bin.rs:75:37
```
=> oci-tar-builder: ensure the output directory exists

Cargo.lock, Cargo.toml, Dockerfile
This PR bumps the `containerd-shim` dependency to include https://github.com/containerd/rust-extensions/pull/151.
This is required to fix #163.
Bumping `containerd-shim` requires also bumping `ttrpc`.
This PR also fixes the `Dockerfile` which stopped working with #126.
=> Bump `containerd-shim` dependency

crates/containerd-shim-wasm/src/services.rs, crates/containerd-shim-wasm/src/services/sandbox_ttrpc.rs
The files generated by the `ttrpc-compiler` do not pass some stylistic clippy's checks.
This means that we need to run `make fix` after running `make build` to prevent CI failures.
This PR prevents clippy from running on the auto-generated.
This means that `make check` won't fail on those files.
This also prevents `make fix` from modifying the auto-generated files.
=> Do not run clippy on auto-generated files

.github/workflows/release.yml, Cargo.lock, Dockerfile, Makefile, crates/containerd-shim-wasmedge/Cargo.toml, crates/containerd-shim-wasmedge/src/bin/containerd-shim-wasmedge-v1/main.rs, crates/containerd-shim-wasmedge/src/executor.rs, crates/containerd-shim-wasmedge/src/instance.rs, test/k8s/Dockerfile
As title. Resolve dependabot's PR.
=> chore: bump wasmedge to 0.13.1 and wasmedge-sdk to 0.9.0

Cargo.lock, crates/containerd-shim-wasm/Cargo.toml
This bumps the version of the shim to `v0.2.0`. After this PR merged, I will tag a new release. 
Could you please take a look? @cpuguy83
=> chore: bump containerd-wasm-shim to version v0.2.0

.github/workflows/ci.yml, .github/workflows/release.yml
PR #185 changes action from [actions-rs/toolchain@v1](https://github.com/actions-rs/toolchain) to [actions-rust-lang/setup-rust-toolchain@v1](https://github.com/actions-rust-lang/setup-rust-toolchain)
There is a key difference between these two actions and that is cache. [actions-rust-lang/setup-rust-toolchain@v1](https://github.com/actions-rust-lang/setup-rust-toolchain) defaults to use "Swatinem/rust-cache", but we already have used this in the CI. 
So this PR removes the redundent cache steps, and disables the rust-cache action in the release CI.
=> fix: remove redundent cache

.github/workflows/ci.yml, .github/workflows/release.yml, Cargo.lock, Dockerfile, Makefile, README.md, crates/containerd-shim-wasmedge/Cargo.toml, crates/containerd-shim-wasmedge/src/bin/containerd-shim-wasmedge-v1/main.rs, crates/containerd-shim-wasmedge/src/executor.rs, crates/containerd-shim-wasmedge/src/instance.rs, test/k8s/Dockerfile
This PR links the wasmedge shims agains the wasmedge static library:
* This simplifies distribution of the shims.
It uses the (new) combination of `standalone` and `static` features of the `wasmedge-sys` crate, which automatically downloads the static library as part of the build process:
* This removes the need to manually install wasmedge.
* Simplifies dependency management: the wasmedge version is now set by the upstream `wasmedge-sdk` crate.
* This requires switching to a git commit for `wasmedge-sdk` until tag `0.10.0` is released.
=> Link against wasmedge static library

.github/workflows/ci.yml
Currently Ubuntu 20.04 and 22.04 are sharing the same cache.
This is a problem as 20.04 and 22.04 ship differente glibc versions.
This prevents the buil scripts compiled and cached in 22.04 from running in 20.04.
`actions-rust-lang/setup-rust-toolchain@v1` uses `Swatinem/rust-cache@v2`, which uses all environment variables matching `RUST*` as hash for the cache key. See the description of `env-vars` [here](https://github.com/marketplace/actions/rust-cache).
This PR adds an environment variable `RUST_CACHE_KEY_OS` so that different OS use different caches.
This fixes #193.
=> [CI] Make Ubuntu 20.04 and 22.04 use different rust cache

.github/dependabot.yml, Cargo.lock, crates/containerd-shim-wasmtime/Cargo.toml
I am tired of bumping wasmtime major version every month so I decided to add a groups config to dependabot to update all wasmtime-related deps together. Hope it works.
Not able to validate the dependabot yml before merging to `main` makes me nervous. Hope this [feature](https://github.com/dependabot/dependabot-core/issues/4605) lands soon!
=> chore: bump wasmtime to 11 and add groups config to dependabot

crates/containerd-shim-wasmtime/src/executor.rs
After #131, only a single arg was allowed to pass causing the shim to fail.  An example is:
```
sudo ctr run --rm --runtime=/home/jstur/.local/bin/containerd-shim-wasmtime-v1 ghcr.io/containerd/runwasi/wasi-demo-app:latest testwasm /wasi-demo-app.wasm echo 'hello'
```
With this change something this works:
```
sudo ctr run --rm --runtime=/home/jstur/.local/bin/containerd-shim-wasmtime-v1 ghcr.io/containerd/runwasi/wasi-demo-app:latest testwasm /wasi-demo-app.wasm echo 'hello'            
hello
exiting  
```
TODO:
- add unit test 
- look into why the shim fails silently in this case (there is a log message if you are following containerd logs:
```
[ERROR] failed to execute workload err=InvalidArg name="wasmtime"
Jul 25 17:56:37 jjs15338 containerd[697]: [ERROR] failed to execute payload …
```
=> Check for existence of args otherwise fail in wasmtime

Cargo.lock, Cargo.toml, crates/containerd-shim-wasm/protos/sandbox.proto, crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasm/src/sandbox/manager.rs, crates/containerd-shim-wasm/src/sandbox/shim.rs, crates/containerd-shim-wasm/src/services/sandbox.rs, crates/containerd-shim-wasmedge/src/instance.rs, crates/containerd-shim-wasmtime/src/instance.rs
This updates Rust-extensions dep to include https://github.com/containerd/rust-extensions/pull/150 which enables using containerd from within the shim.  This is in perp for handling oci artifacts that will be stored in the containerd content store in which we need the containerd address.
=> Pass the containerd address into shim

Dockerfile
This commit fixes the broken Dockerfile that is used in release CI. It adds wasmedge installation step in the build, uses `xx-cargo` instead of cargo, and copies the `sed` command from Docker's build script that allows xx-cargo to be used with pkg-config in build scripts.
Reference
1. Docker's [build script](https://github.com/rumpl/containerd-wasi-shims/blob/main/Dockerfile)
2. xx [issue](https://github.com/tonistiigi/xx/issues/108)
FYI @cpuguy83 @jprendes
=> fix(release): fix the Dockerfile

.github/workflows/release.yml
This commits adds a check to confirm the existance of files in the release subdirectories before attempting to upload to GitHub release. This change helps avoid unnecessary errors in the case where the release subdirectories are empty.
An instance of the failed run this commits tries to resolve is found [here](https://github.com/containerd/runwasi/actions/runs/5718307257).
=> fix: add a stat condition check for uploading release binaries

crates/containerd-shim-wasmedge/Cargo.toml
=> Add crate feature to disable libwasmedge static linking

Cargo.lock, Cargo.toml, crates/containerd-shim-wasm/Cargo.toml
This commit bumps the containerd-shim to 0.4.0 version and all the shims crates and containerd-shim-wasm crate to a new patch version as a preparation for a new release
Closes #162
=> chore: bump containerd-shim to 0.4.0 and bump crates patch version

MAINTAINERS
I'd like to invite @jprendes as a reviewer. He had made sustained commits to runwasi, including his work on linking against WasmEdge static library. He has demonstrated his technical depth and knowledge on this project.
Needs explicit LGTM from @jprendes  and 1/3 of the runwasi Committers according to https://github.com/containerd/project/blob/main/GOVERNANCE.md.
This PR will remain open for 7 days.
=> MAINTAINERS: Add Jorge Prendes(jprendes) as a REVIEWER

Cargo.lock, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasm/src/sandbox/shim.rs
This PR adds a new `stats` function to the implementation of a Task. It uses `cgroups_rs` crate to get the memory stats from cgroup subsystems, which is largely inspired by how containerd runc shim is implemented in rust-extensions repo. 
This is currently work-in-process but I want to get it out there so to collect some early feedback. 
If you want to test it, you can use `ctr task metric <task-name>` to print out the memory usage of the task
```bash
➜  runwasi git:(stats) ✗ sudo ctr task metric testwasm
ID          TIMESTAMP                              
testwasm    seconds:1690930464  nanos:407172844    
METRIC                   VALUE       
memory.usage_in_bytes    18649088    
memory.limit_in_bytes    0           
memory.stat.cache        0           
cpuacct.usage            3545445 …
```
=> feat: add stats function to task

Cargo.lock, Makefile, crates/containerd-shim-wasm/src/sandbox/testutil.rs, crates/containerd-shim-wasmedge/Cargo.toml, crates/containerd-shim-wasmedge/src/lib.rs
See [this comment](https://github.com/containerd/runwasi/pull/210#issuecomment-1663729113)
This PR fixes the static feature being unconditionally enabled, and adds tests to verify static / dynamic linking.
```
$ make test 2>/dev/null | grep linking
test test::check_static_linking ... ok
test test::check_dynamic_linking ... ok
```
@Mossaka @cpuguy83
=> [wasmedge] fix static linking unconditionally enabled

crates/containerd-shim-wasm/src/sandbox/oci.rs, crates/containerd-shim-wasmedge/src/executor.rs, crates/containerd-shim-wasmedge/src/instance.rs, crates/containerd-shim-wasmtime/src/executor.rs, crates/containerd-shim-wasmtime/src/instance.rs
This was part of the code that I was working on when I found https://github.com/containerd/runwasi/issues/194.  I saw it in https://github.com/containerd/runwasi/pull/156/files#diff-94b2ab211987ee0bd5d798ac422f3c3e169b69da929d6684874f72c347671bfeR49 as well so thought we could use it in one location.  
There is a test that is marked as `[skip]` included that could be enabled once #194 is resolved or I can remove it for now.
=> Refactor entrypoint logic to one location

.github/workflows/release.yml, Cargo.lock, Dockerfile, crates/containerd-shim-wasmedge/Cargo.toml, crates/containerd-shim-wasmtime/Cargo.toml, docker-bake.hcl, rust-toolchain.toml, scripts/dockerfile-utils.sh
This PR adds support for building alpine binaries.
The main changes:
* Add a build argument to the Dockerfile to specify the base image.
* Update the bake file to account for the new argument
* Move some of the logic from the Dockerfile to a shell script that handles the different base images.
* The name of the tar archives now end with `-gnu`or `-musl` (for debian and alpine respectively).
* Bumped `wasmedge-sdk` to 0.11.2 (required for building with alpine https://github.com/WasmEdge/wasmedge-rust-sdk/pull/48).
* Add a feature to vendor the dbus crate (so that it links statically)
Result:
```bash
$ docker buildx bake bins-cross tar-cross
$ ls bin
alpine-amd64  alpine-arm64  bullseye-amd64  bullseye-arm64
$ ls bin/alpine-amd64/
containerd-shim-wasmedged-v1  containerd-shim-wasmtimed-v1 …
```
=> Add alpine build

crates/containerd-shim-wasmedge/src/executor.rs, crates/containerd-shim-wasmtime/src/executor.rs
Quick follow up to #219 and #156
=> Use common library function for getting the module name

.gitignore, README.md, crates/containerd-shim-wasm/src/libcontainer_instance/instance.rs, crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasm/src/sandbox/manager.rs, crates/containerd-shim-wasm/src/sandbox/shim.rs, crates/containerd-shim-wasmedge/src/bin/containerd-shim-wasmedge-v1/main.rs, crates/containerd-shim-wasmedge/src/bin/containerd-wasmedged/main.rs, crates/containerd-shim-wasmedge/src/instance.rs, crates/containerd-shim-wasmtime/src/bin/containerd-shim-wasmtime-v1/main.rs, crates/containerd-shim-wasmtime/src/bin/containerd-wasmtimed/main.rs, crates/containerd-shim-wasmtime/src/instance.rs
This PR removes the generics that can be inferred derived from others.
It also makes the actual code more closely match the example in `README.md`, which was missing many `_` generics.
=> Remove redundant generics

benches/containerd-shim-benchmarks/benches/webassembly-benchmarks.rs, crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasm/src/sandbox/manager.rs, crates/containerd-shim-wasm/src/sandbox/mod.rs, crates/containerd-shim-wasm/src/sandbox/shim.rs, crates/containerd-shim-wasmedge/src/bin/containerd-wasmedged/main.rs, crates/containerd-shim-wasmedge/src/instance.rs, crates/containerd-shim-wasmtime/src/bin/containerd-wasmtimed/main.rs, crates/containerd-shim-wasmtime/src/instance.rs
This PR removes the `EngineGetter` trait and replaces it with the use of `Default::default()`.
In the case where an instance would have implemented a non-trivial `EngineGetter`, there are two options:
* If the associated `Engine` type is local to the crate, implement a suitable `Default`.
* Otherwise, use a wrapper struct for the associated `Engine` type and implement a suitable `Default` for the wrapper (and optionally also `Deref`)
=> Remove EngineGetter

Makefile, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasmedge/Cargo.toml, crates/containerd-shim-wasmtime/Cargo.toml
This commit resolves a name clash of the `libcontainer` feature from the containerd-shim-wasm, which undesirably forces all other features to bring in libseccomp and systemd dependencies. By renaming `libcontainer` to `libcontainer_default`, the consumer of the crate can specify `cgroupsv2` to directly access libcontainer's v2 feature without bringing in libseccomp and systemd dependencies. 
This will resolve this concerns @0xE282B0 raised https://github.com/deislabs/containerd-wasm-shims/pull/122#issuecomment-1682388913
FYI @jsturtevant
=> feat: resolve a name clash of the libcontainer features

.github/scripts/build.sh, .github/workflows/ci.yml, README.md, scripts/setup.sh
This consolidates the scripts and came out of https://github.com/containerd/runwasi/pull/238#discussion_r1293544759.
=> Consolidate setup steps to keep in sync

.github/workflows/ci.yml, Makefile, crates/containerd-shim-wasm/src/libcontainer_instance/container_executor.rs, crates/containerd-shim-wasm/src/libcontainer_instance/instance.rs, crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasm/src/sandbox/instance_utils.rs, crates/containerd-shim-wasm/src/sandbox/manager.rs, crates/containerd-shim-wasm/src/sandbox/oci.rs, crates/containerd-shim-wasm/src/sandbox/shim.rs, crates/containerd-shim-wasm/src/sandbox/testutil.rs, crates/containerd-shim-wasmedge/src/executor.rs, crates/containerd-shim-wasmedge/src/instance.rs, crates/containerd-shim-wasmtime/src/executor.rs, crates/containerd-shim-wasmtime/src/instance.rs, crates/containerd-shim-wasmtime/src/oci_wasmtime.rs, crates/oci-tar-builder/src/bin.rs, crates/oci-tar-builder/src/lib.rs, crates/wasi-demo-app/src/main.rs, rustfmt.toml
This commits adds a rustfmt configuration to create three import groups:
1. std, core
2. external
3. local crates
and group all the imports based on these three groups. 
Changed `cargo fmt --all` to `cargo +nightly fmt --all` as this feature isn't stable
=> refactor: group imports 

Cargo.lock, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasm/src/sandbox/instance_utils.rs, crates/containerd-shim-wasmedge/Cargo.toml, crates/containerd-shim-wasmedge/src/instance/instance_linux.rs, crates/containerd-shim-wasmtime/Cargo.toml, crates/containerd-shim-wasmtime/src/instance/instance_linux.rs, crates/oci-tar-builder/Cargo.toml
This PR moves determine_rootdir to containerd-shim-wasm for sharing. It also removes unused dependencies in the repo.
=> Moved determine_rootdir to containerd-shim-wasm

crates/containerd-shim-wasmedge/src/executor.rs
With #78 we inadvertedly stopped preopening the container root.
This means that the wasmedge shim doesn't have access to the container filesystem.
This PR reintroduces preopening the container root with wasmedge.
=> Make wasmedge preopen the container root

crates/containerd-shim-wasm/src/lib.rs, crates/containerd-shim-wasm/src/libcontainer_instance/container_executor.rs, crates/containerd-shim-wasm/src/sandbox/manager.rs, crates/containerd-shim-wasm/src/sandbox/mod.rs, crates/containerd-shim-wasm/src/sandbox/shim.rs, crates/containerd-shim-wasm/src/sandbox/stdio.rs, crates/containerd-shim-wasm/src/sys/unix/metrics.rs, crates/containerd-shim-wasm/src/sys/unix/mod.rs, crates/containerd-shim-wasm/src/sys/unix/networking.rs, crates/containerd-shim-wasm/src/sys/unix/stdio.rs, crates/containerd-shim-wasm/src/sys/windows/metrics.rs, crates/containerd-shim-wasm/src/sys/windows/mod.rs, crates/containerd-shim-wasm/src/sys/windows/networking.rs, crates/containerd-shim-wasm/src/sys/windows/stdio.rs, crates/containerd-shim-wasmedge/src/executor.rs, crates/containerd-shim-wasmedge/src/instance/instance_linux.rs, crates/containerd-shim-wasmedge/src/instance/instance_windows.rs, crates/containerd-shim-wasmtime/src/executor.rs, crates/containerd-shim-wasmtime/src/instance/instance_linux.rs, crates/containerd-shim-wasmtime/src/instance/instance_windows.rs
This PR introduces an RAII wrapper to hande stdio redirection.
The wrapper handles the lifetime of the file descriptors involved.
It also introduces Windows support for stdio redirection.
=> Use an RAII wrapper for stdio redirection

.github/workflows/ci.yml, .gitignore, Makefile, test/k8s/Dockerfile
This PR shares the artifacts created during the build jobs with the e2e test jobs.
It cuts checks times from 20\~25 min to 13\~16 min.
Further improvements can be made by splitting the Ubuntu based jobs and Windows base jobs, since currently Windows builds are in the critical path.
=> Share artifacts between jobs

.github/workflows/action-build.yml, .github/workflows/action-fmt.yml, .github/workflows/action-test-image.yml, .github/workflows/action-test-k3s.yml, .github/workflows/action-test-kind.yml, .github/workflows/ci.yml, .github/workflows/release.yml, Makefile, scripts/setup-linux.sh, scripts/setup-windows.sh
This is a continuation of #267 and further reduces the PR runtime to \~8min
=> Use reusable workflows to split linux and windows builds

Cargo.toml, Dockerfile, rust-toolchain.toml
There is an addition for `resolver=2` applies to the workspace, and the reason for that is to resolve this build warning message
```bash
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```
=> chore: bump rust to 1.72

Cargo.lock, Cargo.toml, Makefile, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasm/src/sandbox/stdio.rs, crates/containerd-shim-wasm/src/sys/unix/stdio.rs, crates/containerd-shim-wasm/src/sys/windows/stdio.rs, crates/wasi-demo-app/Cargo.toml
Containerd passes STDIO as named pipes on windows. The stdio implementation with `libc::dup2([f.as](http://f.as/)_raw_fd(), $fd) }` would error with `invalid handle was specified`.
This checks if it starts with the standard named_pipe path and adds the appropriate `openoptions`.
=> Support passing named pipes in stdio

crates/containerd-shim-wasm/src/libcontainer_instance/instance.rs, crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasm/src/sandbox/testutil.rs, crates/containerd-shim-wasm/src/sys/unix/mod.rs, crates/containerd-shim-wasm/src/sys/unix/signals.rs, crates/containerd-shim-wasm/src/sys/windows/mod.rs, crates/containerd-shim-wasm/src/sys/windows/signals.rs, crates/containerd-shim-wasmedge/src/instance/instance_linux.rs, crates/containerd-shim-wasmtime/src/instance/instance_linux.rs
Small cleanup deduplicating code.
=> Merge both existing `run_wasi_test` implementations

crates/containerd-shim-wasmedge/build.rs, crates/containerd-shim-wasmedge/src/bin/containerd-shim-wasmedge-v1/main.rs, crates/containerd-shim-wasmedge/src/bin/containerd-shim-wasmedged-v1/main.rs, crates/containerd-shim-wasmedge/src/lib.rs, crates/containerd-shim-wasmtime/build.rs, crates/containerd-shim-wasmtime/src/bin/containerd-shim-wasmtime-v1/main.rs, crates/containerd-shim-wasmtime/src/bin/containerd-shim-wasmtimed-v1/main.rs, crates/containerd-shim-wasmtime/src/lib.rs
This follows the PR https://github.com/containerd/rust-extensions/pull/167
=> feat: add version flag to all the shims

Cargo.lock, Cargo.toml, crates/containerd-shim-wasm/src/libcontainer_instance/container_executor.rs, crates/containerd-shim-wasmedge/src/executor.rs, crates/containerd-shim-wasmedge/src/instance/instance_linux.rs, crates/containerd-shim-wasmtime/src/executor.rs, crates/containerd-shim-wasmtime/src/instance/instance_linux.rs
- fixed all the api breakage
- implemented new executor validation logic
=> bump libcontainer to tip of tree

.github/workflows/action-build.yml, .github/workflows/action-test-kind.yml, .github/workflows/action-test-smoke.yml, .github/workflows/ci.yml, .github/workflows/release.yml, Cargo.lock, Cargo.toml, Makefile, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasm/src/libcontainer_instance/container_executor.rs, crates/containerd-shim-wasm/src/sandbox/stdio.rs, crates/containerd-shim-wasm/src/sys/unix/stdio.rs, crates/containerd-shim-wasm/src/sys/windows/stdio.rs, crates/containerd-shim-wasmedge/src/executor.rs, crates/containerd-shim-wasmedge/src/instance/instance_linux.rs, crates/containerd-shim-wasmtime/src/executor.rs, crates/containerd-shim-wasmtime/src/instance/instance_linux.rs
With #260 the stdio `fd` are dangling in the parent shim process.
Normally redirecting the `stdio` would clear the `fd`s.
However, the redirection happens in the `clone3`d child process.
This means that the parent process maintains a dangling cope of the ´fd´s, keps alive by the shim `Instance`s.
The key changes in this PR are:
* `Stdio` now offers a `take` method.
* The `Instance` impls now use `stdio.take()` for the last executor, giving up ownership of the `fd`s.
* Adds a smoke test that used to hang without this change.
The rest of the changes are general fixes:
* Change the `Muxtex` in `Stdio` to an `AtomicCell` ~~(we need two nested ones to be able to implement ´take´)~~
* Add timeouts to the tests in CI
* Update the release workflow, which was using the old path of a moved script
* …
=> Fix dangling fd with stdio

Cargo.lock, crates/containerd-shim-wasmedge/src/executor.rs, crates/containerd-shim-wasmedge/src/instance/instance_linux.rs, crates/containerd-shim-wasmtime/Cargo.toml, crates/containerd-shim-wasmtime/src/executor.rs, crates/containerd-shim-wasmtime/src/instance/instance_linux.rs
This PR returns the actual exit code retirned by the wasm module rather than `0` on success and `137` on failre.
=> Handle wasmtime and wasmedge exit status

Cargo.lock, Cargo.toml
Bump libcontainer to a released version instead of a git rev.
=> Bump libcontainer to 0.2

crates/containerd-shim-wasmedge/src/executor.rs, crates/containerd-shim-wasmtime/src/executor.rs
Currently `wasmedge` and `wasmtime` are mounting the container _cwd_ into the wasi _root_.
This PR changes that so that we mount he container _root_ into the wasi _root_
=> Preopen the container root instead of cwd

Cargo.lock, crates/containerd-shim-wasmedge/Cargo.toml
This PR supersedes https://github.com/containerd/runwasi/pull/309
=> chore: bump wasmedge to 0.12.1

.github/workflows/release.yml
I noticed that the release directory structure was changed in #236 . This commits fixes that. 
It should fix the issue described in #328 
CC @jprendes
=> release: remove extra layer in create release

.github/workflows/action-test-kind.yml, .github/workflows/ci.yml, Makefile
This PR adds k3s e2e tests to wasmtime and kind e2e tests to wasmedge and wasmer.
It does it by adding a parameter to the e2e test in the Makefile, which indicates the runtime to use.
=> Run e2e test with both kind and k3s for all runtimes

Cargo.lock, crates/containerd-shim-wasmedge/Cargo.toml
The new patch release of wasmedge-sdk fixes the issue where it fails to build with musl.
=> Bump wasmedge-sdk with fixed musl issue

Cargo.lock, Cargo.toml, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasm/src/sys/unix/container/instance.rs, crates/containerd-shim-wasm/src/sys/unix/networking.rs
`nix 1.27` doesn't enable features by default, so we need to enable them manually.
Also, libcontainer uses Nix 1.26, and the `Pid` type had changed between the two versions. To work around this, we need to go through the raw `pid_t`.
This supersedes #294
=> Bump nix to 1.27.1

.cargo/config.toml, Cross.toml, Makefile, cross/Dockerfile.gnu, cross/Dockerfile.musl
This PR enables the use of `cross-rs` for building and testing.
```sh
make build-wasmedge CARGO=cross TARGET=x86_64-unknown-linux-musl
```
It also works as an example on how to set up the cross containers for building `runwasi` with `libseccomp`
This PR depends on #331 as otherwise wasmedge wouldn't build on `musl` targets.
Note that the release workflows are not using `cross-rs` which can be done in a follow up PR.
=> Use `cross-rs`

.github/workflows/action-test-k3s.yml, .github/workflows/action-test-kind.yml, Makefile
This PR gathers the containerd and pod logs for k3s and kind whenever the e2e tests fails and uploads them as artifacts for further inspection.
This [CI run](https://github.com/containerd/runwasi/actions/runs/6385816342?pr=346) is an example of what said artifacts look like for both, k3s and kind.
I hope this will help us further debug the root cause of the sporadic e2e failures in CI.
=> Upload k3s/kind logs on failure

crates/containerd-shim-wasmedge/src/instance.rs
It's a feature PR
By the way, please note that this feature currently only functions when dynamically linking the WasmEdge library to the WasmEdge shim.
For building this, you can use the following command:
`cargo build --package containerd-shim-wasmedge --no-default-features`
In addition, I have provided all the WasmEdge runtime demo cases via containerd ([here](https://github.com/CaptainVincent/runwasi/actions/runs/6150982952)), including the `wasinn plugin` demo related to this feature. Considering that these demos may only be supported with the WasmEdge shim, I plan to relocate and maintain them under the WasmEdge or Second State Org's repository. At the same time, I will ensure that they run demos daily in CI and guarantee that these demos are always executed based on the latest …
=> feat: Support wasmedge plugins

Cargo.lock, Cargo.toml
This allows for artifact field in the spec: https://github.com/containerd/runwasi/pull/147#discussion_r1344770351
=> Bump oci spec package

Makefile, test/k3s/bootstrap.sh
Sporadically k3s would fail to bootstrap, see
* missing file from install: https://github.com/containerd/runwasi/issues/322#issuecomment-1751267331
* kube-sys pods never start: https://github.com/containerd/runwasi/actions/runs/6455790697/job/17524166280
This PR tries to mitigate this by re-bootstrapping k3s when that happens.
This change uses a timeout of 40s for k3s bootstrapping. If that fails, it uninstalls k3s, reinstalls it, and tries again.
This would continue until it succeeds or the CI timeout of 5min is hit.
Note that in the case where the kube-sys pods never show up, simply restarting the systemd service is not enough (I tired this in one of the many many attempts), which indicates that a complete reinstall is a better option.
=> Retry bootstrapping k3s on failure

Cargo.lock, Cargo.toml, crates/containerd-shim-wasm/Cargo.toml
This should fix #347 (at least the CI failures, not the follow up issue discussed in  https://github.com/containerd/runwasi/issues/347#issuecomment-1755433335 and on [slack](https://cloud-native.slack.com/archives/C04LTPB6Z0V/p1696946987284239?thread_ts=1696287505.124309&cid=C04LTPB6Z0V))
=> Bump libcontainer to include UB fix

crates/containerd-shim-wasm/src/sandbox/cli.rs
=> Use fallback if `git_version` fails

.github/workflows/action-build.yml, .github/workflows/action-test-k3s.yml, .github/workflows/action-test-kind.yml, .github/workflows/action-test-smoke.yml, .github/workflows/ci.yml, Makefile, crates/containerd-shim-wasmedge/src/tests.rs, scripts/setup-cross.sh, scripts/test-runner.sh, scripts/validate-docs.sh
This PR switches CI to use the `cross-rs` support introduced in #332.
This should unblock #356.
This PR uses `cross-rs` for the linux builds of the shims. It generates a `linux-musl` and a `linux-gnu` artifacts using `musl` and `glibc` respectively.
It also stops building the shims on `ubuntu-20.04`. Since the `cross-rs` build happens in a container it is not necessary to build on different OS versions. However, we keep running e2e tests in `ubuntu-20.04` to maintain test coverage on an OS running `cgroups-v1`.
The e2e tests are switched to use the `musl` build of the shims, as this would unblock #356.
Since `cross-rs` uses an older `glibc` version, it might be possible to also enable e2e tests using `glibc`, but I suggest we defer that to another PR after #356 is merged.
There are some …
=> Use `cross-rs` for building in CI

test/k8s/Dockerfile
Updating to use more recent versions of kubernetes and kind
=> chore: Use latest kind and k8s release

crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasm/src/sandbox/mod.rs, crates/containerd-shim-wasm/src/sandbox/shim.rs, crates/containerd-shim-wasm/src/sandbox/sync.rs, crates/containerd-shim-wasm/src/sys/unix/container/instance.rs, crates/containerd-shim-wasm/src/sys/windows/container/instance.rs, crates/containerd-shim-wasm/src/testing.rs
This PR simplifies the API around the `Instance::wait` method and around `TaskState` and `InstanceData`.
Fixes #339.
Note that a side effect of this PR is that it fixes #326 but it shouldn't be considered a substitute for #340.
=> Remove complexity from wait API

Makefile
This PR addresses two issues after #359 when running `make test/k8s-wasmtime` locally.
First, the `TARGET` is not being set properly. Since `TARGET` was already set when re-invoking `$(MAKE)` it gets the prior value. Example output:
```
-f /home/jstur/projects/runwasi/dist/bin/containerd-shim-wasmtime-v1 ] || make install-wasmtime CARGO=cross PREFIX="/home/jstur/projects/runwasi/dist" OPT_PROFILE="debug"
make[1]: Entering directory '/home/jstur/projects/runwasi'
cross build --target=x86_64-unknown-linux-gnu -p containerd-shim-wasmtime
```
Second, cross has issues when switching targets: https://github.com/cross-rs/cross/wiki/FAQ#glibc-version-error.  I ran into this only my local set up, where the first step of cross (after fixing the above) would error out with
```
=> => naming to …
```
=> Fix issue running k8s and cross locally

Makefile, crates/containerd-shim-wasm/src/sandbox/shim.rs
When removing the mounting code we also removed the network setup: https://github.com/containerd/runwasi/pull/327#issuecomment-1730071090
Ends up this is required as youki is only setting the Pid and User namespaces: https://github.com/containers/youki/blob/ba4a10f4a09b0360eeb38ab70a95adc986b2b9da/crates/libcontainer/src/process/container_intermediate_process.rs#L70
=> Add the shim to to the network NS specified

.github/workflows/release.yml
Instead of checking if the `github:containerd:runwasi-committers` is an owner of the crate, we always add it as an owner. 
This may help to resolve the error we encountered at this run: https://github.com/containerd/runwasi/actions/runs/6699464559/job/18203943248#step:7:12
=> ci: add runwasi-committee to owner of the crate

Cargo.toml
In cargo, it is possible to specify a local path and a register version for one dep (see https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations). 
What this means for us is that we can keep using local `containerd-shim-wasm-test-modules` for development. At the same time, when we do `cargo publish`, it will resolve to use the remote version of `containerd-shim-wasm-test-containers` from crates.io.
=> chore: add published version of wasm-test-modules dep

.github/workflows/release.yml
I triggered release CI for all three shims (wasmtime, wasmedge and wasmer). Two out of three encountered a timeout issue so I am doubling the timeout duration for the build action
See failed runs:
- https://github.com/containerd/runwasi/actions/runs/6699073525/job/18202498689#step:7:650
- https://github.com/containerd/runwasi/actions/runs/6699079435/job/18202521220#step:7:638
=> ci: double the timeout duration

Cargo.lock, Cargo.toml
Add a published version to containerd-shim-wasm dep for all the shims. Bumped the patch version so that the containerd-shim-wasm-test-modules could be published again. 
I will need to publish crates in a particular order
`containerd-shim-wasm-test-modules` -> `containerd-shim-wasm` -> shims
=> chore: bump patch version of shims and add containerd-shim-wasm version

.github/workflows/release.yml
The release of `containerd-shim-wasm` crate failed at the cargo publish step saying that `protoc` was not found. Thus I am adding build env to the release job.
=> ci: add build env to release job

.github/workflows/cargo-owner.yml
This PR is an attempt to create a manually trigger GH action to add github.actor (the github user who triggered the action) as an owner to a crate on crates.io published by the bot.
=> add owner of the github actor to a crate

RELEASE.md
This PR improves the release docs in the following ways:
1. add a section describing the release sequence needed to perform
2. add a section explaining how local and release versions of dependency are handled by Cargo.
=> docs: add release sequence to RELEASE.md

Cargo.lock, crates/containerd-shim-wasmedge/Cargo.toml, crates/containerd-shim-wasmedge/src/tests.rs
This PR removes the dependency on `wasmedge-sys`.
This depdency was only used to test that a symbol is statically / dinamically linked in the binary.
This PR inlines the FFI symbol instead of using the crate dependency.
The risk of depending on `wasmedge-sys` is that the version could drifts from what `wasmedge-sdk` uses.
In that case, the test would be probing the wrong symbol, and it may silenly succeed when it should fail.
The selected symbol for the probe is expected to remain unchaged across different versions of wasmedge.
If it ever changes, then compilation should fail, indicating that the symbol needs to be updated.
=> remove wasmedge-sys dependency

Cargo.toml, crates/containerd-shim-wasm-test-modules/Cargo.toml, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasmedge/Cargo.toml, crates/containerd-shim-wasmer/Cargo.toml, crates/containerd-shim-wasmtime/Cargo.toml
This PR aims to use more restrictive dependency versions in our `Cargo.toml` file.
**Policy Compliance**: To adhere to the "no wildcard version" policy enforced by crates.io, making our package more compliant and easier to publish. See https://github.com/containerd/runwasi/actions/runs/6715767237/job/18251185616#step:7:794
**Reduced Risks**: By pinning our dependencies to major versions, we reduce the risks associated with unexpected breaking changes in newer versions.
I will give another try to release `containerd-shim-wasm` at `v0.4.0`
=> fix(Cargo.toml): restrict wildcard version to major versions

crates/containerd-shim-wasm/src/sandbox/cli.rs, crates/containerd-shim-wasmedge/src/main.rs, crates/containerd-shim-wasmer/src/main.rs, crates/containerd-shim-wasmtime/src/main.rs
This PR adds a `shim_version` parameter to `shim_main` macro to relex the version for shim implementations.
=> feat: support any shim version in `shim_main`

crates/containerd-shim-wasm/src/container/context.rs, crates/containerd-shim-wasm/src/container/engine.rs, crates/containerd-shim-wasm/src/container/mod.rs, crates/containerd-shim-wasm/src/sandbox/containerd.rs, crates/containerd-shim-wasm/src/sys/unix/container/executor.rs, crates/containerd-shim-wasm/src/sys/unix/container/instance.rs, crates/containerd-shim-wasmedge/src/instance.rs, crates/containerd-shim-wasmer/src/instance.rs, crates/containerd-shim-wasmtime/src/instance.rs
This PR makes a few changes to the the `RuntimeContext` API regarding OCI:
- use an enum which makes the API clearer when using.  
- changes the way the wasm layers are filtered based on https://github.com/containerd/runwasi/pull/147#discussion_r1371838109 
- uses a single entrypoint function instead of 2.  I was initially confused when looking at `entrypoint` vs `wasiEntrypoint` and thought this might simplify it. Feedback welcome.
=> Consolidate the RuntimeContext API to use one EntryPoint and expose Source for WASI files

MAINTAINERS
Based on the significant contributions to this project, I would like to propose we promote @jsturtevant to committer.
=> Promote @jsturtevant to committer

README.md
I've fixed the missing link in README.md .
The section #Building is not exist now.
=> Fix missing link in README.md

scripts/setup-linux.sh
When I've run `make build`.
I've got following error without `libzstd-dev`.
```
Compiling wasmedge-sdk v0.13.2
Compiling containerd-shim-wasmedge v0.3.1 (/Users/tsakao/runwasi/crates/containerd-shim-wasmedge)
error: linking with `cc` failed: exit status: 1
|
= note: LC_ALL="C" ...omit...
= note: /usr/bin/ld: cannot find -lzstd
collect2: error: ld returned 1 exit status
error: could not compile `containerd-shim-wasmedge` (bin "containerd-shim-wasmedge-v1") due to previous error
make: *** [Makefile:76: build-wasmedge] Error 101
```
Signed-off-by: Takumasa Sakao <tsakao@zlab.co.jp>
=> Add libzstd-dev as dependencies

Makefile, test/k8s/deploy.oci.yaml
The image name expected in https://github.com/containerd/runwasi/blob/ec3d24d9abf0ff007ab56d07fbe040b1753d6b20/README.md#L289 is `ghcr.io/containerd/runwasi/wasi-demo-oci`.
But the image name created by `make test-image/oci` is `wasi-demo-app`.
So I've fixed the image name to `wasi-demo-oci`.
Signed-off-by: Takumasa Sakao <tsakao@zlab.co.jp>
=> Fix image name of test-image/oci

Makefile
This PR adds a few commands to the Makefile, and thus the CI/CD pipelines, to verify the workflow could be deleted successfully, not stucking in a terminating status forever. 
Related to issue #418
=> test(*): verify pods get deleted successfully

Makefile, README.md, crates/oci-tar-builder/README.md, test/k3s/bootstrap.sh, test/k8s/Dockerfile.oci
Containerd versions have been released and updating docs.
=> Update docs and scripts for latest on OCI images

crates/containerd-shim-wasm/src/container/context.rs, crates/containerd-shim-wasmedge/src/instance.rs, crates/containerd-shim-wasmer/src/instance.rs, crates/containerd-shim-wasmtime/src/instance.rs
This PR is a preferred way to refactor the usage of `Source` into a `as_bytes()` function in Context. It does not change the APIs of the Engine trait. Closes #448
=> refactor(*): add source.as_bytes()

CONTRIBUTING.md
=> Add guidance for adding and removing shims from project

.github/workflows/release.yml, RELEASE.md
This draft PR adds cosign signing for the released binaries. It is WIP.
I am testing releases in my own forked repo: https://github.com/Mossaka/runwasi/actions/runs/7634841458
Related to #417
=> feat(ci): add cosign to sign the released binaries

.github/workflows/release.yml
This commit excludes containerd-shim-wasm-test-modules from binary signing, packaging and publishing.|
Closes #497 FYI @devigned
=> ci(release): exclude wasm-test-modules crate

Cargo.lock, Makefile, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasm/src/container/engine.rs, crates/containerd-shim-wasm/src/sandbox/containerd/client.rs, crates/containerd-shim-wasm/src/sandbox/mod.rs, crates/containerd-shim-wasm/src/testing.rs, crates/containerd-shim-wasmtime/Cargo.toml, crates/containerd-shim-wasmtime/src/instance.rs, crates/containerd-shim-wasmtime/src/tests.rs, crates/oci-tar-builder/Cargo.toml, crates/oci-tar-builder/src/lib.rs
After some feedback we found some runtimes require ability to individually pre-compile layers.  This attempts to address that ability. 
This also fixes a bug that was introduced when adding pre-compilation where the media types were being overwritten.
=> Pre-compile each layer individually

crates/containerd-shim-wasm/src/sandbox/containerd/client.rs
Streams content to the containerd store in 15MB chunks in order to support precompiling larger layers
Tested with 200 MB Spin app
=> fix(precompilation): support streaming layer content in 15MB chunks

crates/containerd-shim-wasm/src/sandbox/containerd/client.rs
this is to resolve my comments made in PR #492 in an effort to make the code a bit more idiomatic and readable
=> refactor(precompile): make code a bit more readable

crates/oci-tar-builder/src/bin.rs
After discussions with OCI group we need to have something with in the Image Config to make it unique https://github.com/opencontainers/image-spec/pull/1173 otherwise existing tooling might not pick it up.  See https://github.com/spinkube/spin-operator/issues/40#issuecomment-1978776234 for an example with CRI.
=> Add hash of layers to make Unique ImageID for existing tooling

Cargo.lock, Cargo.toml
Updates to use the released version of rust-extensions which contains the cgroups parsing. With this fix and many others that have come in the last few weeks I think we can do a release of runwasi.
=> Update rust-extensions to 0.7.1

Cargo.lock, crates/containerd-shim-wasm-test-modules/Cargo.toml
The test modules crate already has a tag https://github.com/containerd/runwasi/releases/tag/containerd-shim-wasm-test-modules%2Fv0.4.0  so this bumps it to 0.4.1 so we can release it properly since it failed last time we tried: https://github.com/containerd/runwasi/actions/runs/7935545087. 
This is needed for the release when trying a dry-run:
```
Caused by:
failed to select a version for the requirement `containerd-shim-wasm-test-modules = "^0.4.0"`
candidate versions found which didn't match: 0.3.1, 0.3.0
```
=> Bump test module crate version

.github/workflows/release.yml, Makefile
The [0.5.0 release](https://github.com/containerd/runwasi/actions/runs/8351251493) is failing due to missing `  no matching package named `oci-tar-builder` found`.  After attempting to release this package the [release build](https://github.com/containerd/runwasi/actions/runs/8362454303/job/22893107967) failed with:
```
error: package ID specification `containerd-shim-oci-tar-builder` did not match any packages
```
This make the updates to the makefile to support building and publishing this package.  At a later time, we can build the `oci-tar-builder` binary and create a release artifact but for now we can release the library as is.
=> Enable building and release of oci-tar-builder

crates/oci-tar-builder/Cargo.toml
[Cargo publish](https://github.com/containerd/runwasi/actions/runs/8364790324/job/22901153910) requires these fields but interestingly `publish --dry-run` doesn't tell you this when testing with it.
https://doc.rust-lang.org/cargo/reference/publishing.html#before-publishing-a-new-crate
=> Add Description and license to oci-tar-builder cargo.toml

.github/workflows/release.yml
Release failed because sed is different on Linux/macos 🤕 
Also adds https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name so can see what ran with out having to open the action logs
=> Fix for running sed on Linux for release pipeline

.github/workflows/action-build.yml, .github/workflows/action-fmt.yml, .github/workflows/action-sign.yml, .github/workflows/action-test-image.yml, .github/workflows/action-test-k3s.yml, .github/workflows/action-test-kind.yml, .github/workflows/action-test-smoke.yml, .github/workflows/ci.yml, .github/workflows/release.yml
this commit merges the build step in the release action and the one in the ci action since they share a large overlap code.
the build step not only builds the binary, but signs it, and upload as action artifacts. this step is now running for every ci run, including PR and release pipeline.
=> ci(*): merge build action

.github/dependabot.yml, .github/workflows/action-fmt.yml, .github/workflows/action-test-image.yml, .github/workflows/action-test-k3s.yml, .github/workflows/action-test-kind.yml, .github/workflows/action-test-smoke.yml
this commit updates the checkout workflow to v4 and add a new rule to dependabot to bump github action versions
closes #558  #557
=> ci(*): update checkout to v4 and add gh action to dependabot

README.md
this commit clarifies how the built binary works and removes duplicated demo sections that tried to show the same thing with different runtimes.
Closes #567
=> docs: clarify how the binary works

Makefile
Through the [Demo](https://github.com/containerd/runwasi/blob/73df3507171080f5146e5464f29f2aca29dd9ce6/README.md?plain=1#L199) in the README, the following error happened.
```bash
ls -la $(which rustc)
-rwxr-xr-x 14 ubuntu ubuntu 15428432 May  4 11:05 /home/ubuntu/.cargo/bin/rustc
rustc --version
rustc 1.75.0 (82e1608df 2023-12-21)
sudo rustc --version
sudo: rustc: command not found
sudo make --trace install
/bin/sh: 1: rustc: not found
/bin/sh: 1: rustc: not found
/bin/sh: 1: rustc: not found
/bin/sh: 1: rustc: not found
Makefile:76: target 'build-wasmedge' does not exist
cargo build --target= --target-dir=./target/ -p containerd-shim-wasmedge
/bin/sh: 1: rustc: not found
/bin/sh: 1: rustc: not found
/bin/sh: 1: rustc: not found
make: cargo: No such file or directory
make: *** …
```
=> Makefile: Define `RUSTC` to avoid "rustc: not found" during `sudo make install`

Makefile
To follow:
- https://github.com/containerd/runwasi/pull/578#issuecomment-2094644975
- https://github.com/containerd/runwasi/blob/6a76c896e4846d416d6b4973ef37645ca738aa3b/README.md?plain=1#L210
=> Makefile: Remove `build` dependency from `install`

Cargo.lock, Cargo.toml, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasm/src/sandbox/cli.rs, crates/containerd-shim-wasm/src/sandbox/containerd/client.rs, crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasm/src/sandbox/instance_utils.rs, crates/containerd-shim-wasm/src/sandbox/shim/cli.rs, crates/containerd-shim-wasm/src/sandbox/shim/instance_data.rs, crates/containerd-shim-wasm/src/sandbox/shim/instance_option.rs, crates/containerd-shim-wasm/src/sandbox/shim/local.rs, crates/containerd-shim-wasm/src/sandbox/shim/task_state.rs, crates/containerd-shim-wasm/src/sys/unix/container/executor.rs, crates/containerd-shim-wasm/src/sys/unix/container/instance.rs, crates/containerd-shim-wasm/src/sys/unix/metrics.rs, crates/containerd-shim-wasm/src/sys/unix/networking.rs
this commit adds tracing instrument macros to functions in the containerd-shim-wasm crate to capture spans of each function including its parameters and results.
these spans can be in turn be collected using tracing-opentelemetry and opentelemetry SDK at the shim binary level and output to collectors like Jeager endpoint.
Demo: https://github.com/Mossaka/runwasi/tree/otel-wasmtime
=> feat(tracing): add tracing instruments to containerd-shim-wasm

Cargo.lock, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasm/src/sandbox/cli.rs, crates/containerd-shim-wasm/src/sandbox/containerd/client.rs, crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasm/src/sandbox/instance_utils.rs, crates/containerd-shim-wasm/src/sandbox/shim/cli.rs, crates/containerd-shim-wasm/src/sandbox/shim/instance_data.rs, crates/containerd-shim-wasm/src/sandbox/shim/instance_option.rs, crates/containerd-shim-wasm/src/sandbox/shim/local.rs, crates/containerd-shim-wasm/src/sandbox/shim/task_state.rs, crates/containerd-shim-wasm/src/sys/unix/container/executor.rs, crates/containerd-shim-wasm/src/sys/unix/container/instance.rs, crates/containerd-shim-wasm/src/sys/unix/metrics.rs, crates/containerd-shim-wasm/src/sys/unix/networking.rs, crates/containerd-shim-wasmtime/Cargo.toml
=> making `tracaing::instrument` macro optional

Cargo.lock, Cargo.toml
this will grab the latest changes that remove the `chdir` syscall and hugely improve the start up performance of the shims
=> chore: bump youki libcontainer to v0.3.3

Cargo.lock, Cargo.toml, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasmedge/Cargo.toml, crates/containerd-shim-wasmer/Cargo.toml, crates/containerd-shim-wasmtime/Cargo.toml
#601 is a major improvement over the start up performance of the shims, and this PR bumps the minor change of the core crate and all shims as a preparation for new releases.
=> release: batch-bump minor version of shims and core crate

crates/containerd-shim-wasm/src/container/path.rs
As the return-position impl trait in trait (RPITIT) feature is stable since [Rust 1.75.0
](https://blog.rust-lang.org/2023/12/28/Rust-1.75.0.html#async-fn-and-return-position-impl-trait-in-traits)
=> Use RPITIT in `PathResolve`

crates/containerd-shim-wasm/src/sys/unix/container/executor.rs
this commit imrpoves the error message for exec function, particularlly when the user forgot to provide Wasm file path as the arg0 for the container, it will log an error message in containerd
Related https://github.com/containerd/runwasi/issues/637
=> Improved error message for `Executor::exec`

Cargo.lock, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasm/src/sandbox/containerd/client.rs
This change removes the dependency on `prost-types`, which otherwise needs to be kept in sync with the version in `containerd-client` (see for example  https://github.com/containerd/runwasi/pull/651)
=> Remove dependency on prost-types

Cargo.lock, crates/containerd-shim-wasm/src/testing.rs, crates/oci-tar-builder/Cargo.toml, crates/oci-tar-builder/README.md, crates/oci-tar-builder/src/bin.rs, crates/oci-tar-builder/src/lib.rs, crates/wasi-demo-app/build.rs
The CNCF wg-wasm has published an [OCI artifact format](https://tag-runtime.cncf.io/wgs/wasm/deliverables/wasm-oci-artifact/) for packaging wasm modules and components.  The artifact can be produced locally by running the `--as-artifact` flag:
```
cargo run --bin oci-tar-builder -- --name wasi-demo-oci --repo ghcr.io/containerd/runwasi --tag latest --as-artifact --module ./target/wasm32-wasi/debug/wasi-demo-app.wasm -o target/wasm32-wasi/debug/img-oci-artifact.tar
regctl image import localhost:5000/wasi-artifact:latest target/wasm32-wasi/debug/img-oci-artifact.tar
```
```
regctl manifest get localhost:5000/wasi-artifact:latest
Name:                                localhost:5000/wasi-artifact:latest
MediaType:                           application/vnd.oci.image.manifest.v1+json
Digest: …
```
=> Add ability to generate new artifact type

Makefile, README.md, crates/containerd-shim-wasm/src/container/engine.rs, test/k8s/deploy.oci.yaml
This is a follow up to https://github.com/containerd/runwasi/pull/631 and adds tests to test the artifact type defined at https://tag-runtime.cncf.io/wgs/wasm/deliverables/wasm-oci-artifact/
This mostly worked out of the box. A couple minor notes that will be working to resolve upstream:
- Using the containerd CRI interface works with this, containenrd [CTR has a bug](https://github.com/containerd/containerd/issues/10179#issuecomment-2278801199) in it that blocks this being used. 
- The pod spec also needs a command specified otherwise the pod will not start.
=> Add e2e tests for Wasm OCI artifact

.github/workflows/benchmarks.yml
the setup-rust-toolchain should respect the rust-toolchains.toml and disable the warnings flag to make it behave the same as other CI actions we have.
=> benchmark: fix the CI failure

Cargo.lock, Cargo.toml, crates/containerd-shim-wasm/src/container/context.rs, crates/containerd-shim-wasm/src/sys/unix/container/executor.rs, crates/containerd-shim-wasmedge/src/instance.rs, crates/containerd-shim-wasmer/src/instance.rs, crates/containerd-shim-wasmtime/src/instance.rs
this commit uses the new setup_envs() method from libcontainer and brings the following changes:
1. the Executor trait now provides a no-op for setup_envs, which means youki is no longer changing shim process's environment variables.
2. the container env vars are passed down to WASI context, meaning only the Wasm modules can see container env vars.
3. This sets a clear boundary between shim process and wasm workloads.
Note that the wasm runtime like Wasmtime is still running on the shim process, which means they will still see shim's env vars passed down from containerd
see more details at #619 
TODO:
=> core/container/context: container env vars are only passed to WASI

crates/containerd-shim-wasmtime/src/instance.rs
small refactoring and formating over the wasmtime shim.
=> wasmtime: tidy up

crates/containerd-shim-wasm/src/container/context.rs, cross/Dockerfile.gnu, cross/Dockerfile.musl, scripts/setup-containerd.sh, scripts/setup-linux.sh
I setup a new dev environment and wanted to get the project running on my OSX machine. I installed a fresh Linux VM and was able to run `make build` and `make test` with this setup.
I encountered one test failure. I don't believe this failure would only impact me as the oci_spec default for environment variables sets 2 environment variables. So I set the 
```rust
impl Default for Process {
fn default() -> Self {
Process {
....
// Sets linux default enviroment for binaries and default xterm emulator
env: vec![
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin".into(),
"TERM=xterm".into(),
]
```
=> Updated Scripts for setup new dev environment

Cargo.lock, crates/oci-tar-builder/Cargo.toml
removes the native-tls dependency from oci-tar-builder and uses rustls-tls instead. This is done to avoid the openssl dependency
note that: if the `opentelemetry` feature is turned on, the containerd-shim-wasm crate will still use native-tls due to the fact that opentelemetry-http uses the default features of reqwest. See more on https://github.com/open-telemetry/opentelemetry-rust/issues/936.
=> oci-tar-builder/Cargo: remove native-tls deps

CONTRIBUTING.md, crates/containerd-shim-wasm/CHANGELOG.md
add a draft of the changelog for containerd-shim-wasm following the https://keepachangelog.com/en/1.1.0/ format. The changelog starts from the `containerd-shim-wasm/v0.6.0` to HEAD. it is expected that the future PRs will update the changelog with the changes made in the PRs.
=> containerd-shim-wasm/CHANGELOG: add initial draft of changelog

Cargo.lock, Cargo.toml, crates/containerd-shim-wasm/Cargo.toml
Bump version to 0.7.0 for containerd-shim-wasm to include the latest features and bug fixes.
=> Release containerd-shim-wasm: bump version to 0.7.0

.github/workflows/release.yml
forked repo cannot publish to crates.io
=> .github/workflows/release: no cargo publish if the repo is not upstream

crates/containerd-shim-wasmtime/src/instance.rs
Check the `wasm` binary type and choose proper precompilation method.
=> Fix wasmtime precompilation

Cargo.lock, Cargo.toml, crates/containerd-shim-wasm/src/testing.rs, crates/containerd-shim-wasmtime/Cargo.toml, crates/containerd-shim-wasmtime/src/http_proxy.rs, crates/containerd-shim-wasmtime/src/instance.rs, crates/containerd-shim-wasmtime/src/tests.rs
This patch adds graceful shutdown functionality to the Wasmtime shim server loop. The shutdown process works as follows:
- The code that spawns the top-level loop creates a `CancellationToken`, which is shared across all cancellable tasks.
- A tracker is used to manage any tasks spawned within the server loop.
- A signal handler is installed to listen for signals. Upon receiving the first `Interrupt` signal, it calls cancel and waits for the server task to finish gracefully, allowing all spawned tasks to complete.
- On receiving a second `Interrupt` signal, the server loop exits immediately.
- Similarly, upon receiving a `Terminate` signal, the server loop finishes abruptly.
- The return code indicates which of these shutdown scenarios occurred. If the server has finished abruptly the …
=> Add graceful server shutdown

Cargo.lock, Cargo.toml, crates/containerd-shim-wasm/Cargo.toml, crates/oci-tar-builder/Cargo.toml
beep boop, I'm pretending to be dependabot.
Bump the version of most dependencies.
Notably missing:
* **otel**, as it's a big breaking change.
* **oci-spec**, as we need to wait for youki to bump it as well, and introduces a few breaking changes.
* **wasmer**, as they pinned wat, and cargo fails to resolve it.
* **mio**, needs to match the version from wasmer
* **protobuf**, see https://github.com/containerd/rust-extensions/issues/295
* **wasmedge**, as it introduces some breaking changes
=> chore(deps): Bump version of most dependencies

crates/containerd-shim-wasm/src/lib.rs
fixes https://github.com/containerd/runwasi/issues/708
=> re-export containerd_shim::Config for runwasi consumers

.github/workflows/action-test-k3s.yml, .github/workflows/action-test-kind.yml, Makefile
This PR attempts to fix the CI sporadic failures by increasing the timeout when waiting for the deployment to be available in the k8s tests.
=> Increase k8s tests timeout

README.md
I believe it is past time to remove the alpha notice in the readme. This PR removes that notice on the readme.
=> Remove the alpha notice in the readme

Makefile
Even after the increase in the timeouts in #709, we are still seeing CI failures.
This PR further increases that timeout.
=> Further increate CI timeout

Makefile, crates/containerd-shim-wasmtime/src/tests.rs
CI is not capturing failures to build tests, this PR intends to fix that as the wasmtime tests are currently failing to build.
=> Fix exit code in CI

Cargo.lock, crates/containerd-shim-wasmer/Cargo.toml
We can now switch back to `wasmer` from crates.io 🎉
=> Switch to wasmer from crates.io

Cargo.lock, Cargo.toml, benches/containerd-shim-benchmarks/benches/wasmedge-benchmarks.rs, crates/containerd-shim-wasm/CHANGELOG.md, crates/containerd-shim-wasmtime/src/http_proxy.rs, crates/containerd-shim-wasmtime/src/instance.rs
This patch changes `wasm` instance allocation strategy from `OnDemand` to `PoolAllocator` which increase a performance of creating a per request instances for components targeting `wasi/http` world.
Here, before and after throughput, for a minimum handler that responds with `Hello World`, shows 10x improvement:
Before:
```
hey -n 10000 -c 10 http://127.0.0.1:8080
Summary:
Total:        2.6978 secs
Slowest:      0.0135 secs
Fastest:      0.0007 secs
Average:      0.0027 secs
Requests/sec: 3706.6977
Response time histogram:
0.001 [1]     |
0.002 [1323]  |■■■■■■■■
0.003 [6765]  |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.005 [1769]  |■■■■■■■■■■
0.006 [123]   |■
0.007 [7]     |
0.008 [1]     |
0.010 [4]     |
0.011 [4]     |
0.012 [2]     |
0.013 [1]     |
Latency distribution:
10% in 0.0019 …
```
=> Use instance pool allocation strategy for wasmtime shim

Cargo.lock, Makefile, crates/containerd-shim-wasm-test-modules/build.rs, crates/oci-tar-builder/README.md, crates/wasi-demo-app/.cargo/config.toml, rust-toolchain.toml
Rust 1.81.0 now issues a warning for the usage of wasm32-wasi target and suggests users to switch to wasm32-wasip1 target. Since we have bumped the minimal rustc version to 1.81.0 in rust-toolchain.toml, we should switch to this new target.
This commit does a whole replace of 'wasm32-wasi -> wasm32-wasip1'.
=> chore: switch to wasm32-wasip1 target

.github/workflows/release.yml, RELEASE.md, scripts/extract-changelog.sh
the release workflow will use the script to extract the changelog and uses it to create a release note. It also uses tag name to determine if the release is pre-release or not.
Verified that release works in a forked repo: https://github.com/Mossaka/runwasi/actions/runs/11243618268
=> scripts, .github/workflows: add script to extract changelog

crates/containerd-shim-wasm/CHANGELOG.md, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasm/src/lib.rs, crates/containerd-shim-wasm/src/test/mod.rs, crates/containerd-shim-wasm/src/test/signals.rs, crates/containerd-shim-wasm/src/testing.rs
This PR adds test for sending signals to containers.
This is the first step towards fixing #755.
Running:
```
USE_LIBC=0 cargo test -p containerd-shim-wasm -- test::signals::test_handling_signals --exact --show-output --nocapture --ignored
```
is very likely to stall
While running:
```
USE_LIBC=1 cargo test -p containerd-shim-wasm -- test::signals::test_handling_signals --exact --show-output --nocapture --ignored
```
does succeed without problems.
The main difference is that the first one uses `tokio::signal`, while the second one uses `libc::signal`.
Commenting out the `containerd::Client` code in `crates/containerd-shim-wasm/src/sys/unix/container/instance.rs` prevents tokio from being used in the shim, and both versions of the test pass reliably.
=> Add test for signals

crates/containerd-shim-wasm/CHANGELOG.md, crates/containerd-shim-wasm/src/sandbox/instance_utils.rs, crates/containerd-shim-wasm/src/sandbox/shim/instance_data.rs, crates/containerd-shim-wasm/src/sys/unix/container/instance.rs
This PR reuses the container returned by `libcontainer` instead of reloading it from disk every time.
Note: some of the functions removed here were part of the public API, probably incorrectly so.
=> [chore] minor cleanup

Makefile
If TARGET is empty, then there is a double '/'. This commit fixes this issue
=> Makefile: fixed the install path issue

.github/workflows/benchmarks.yml, benches/containerd-shim-benchmarks/Cargo.toml, benches/containerd-shim-benchmarks/README.md, benches/containerd-shim-benchmarks/benches/wasi-demo-app-benchmarks.rs
This commit adds a new benchmark for running the shims end-to-end on wasi-demo-{app, oci} to print 'hello'.
=> benches: add a new wasi-demo-{app, oci} benchmark

Cargo.lock, Cargo.toml, crates/containerd-shim-wasm/src/container/context.rs, crates/containerd-shim-wasm/src/sandbox/containerd/client.rs, crates/oci-tar-builder/src/lib.rs
This PR bumps `youki`.
The bump in youki also forces us to bump oci-spec which includes breaking changes to the `Digest` type.
This PR also deals with those breaking changes.
The new version hasn't been released yet so it uses a git dependency.
We should revert to a published version once it's available.
=> [chore] bump youki

.github/actions/run-hey-load-test/action.yml, .github/workflows/benchmarks.yml, scripts/parse-hey.py
this commit adds `auto-push: true` to the benchmark-action/github-action-benchmark
which allows it commit changes and push to gh-pages branch and display charts
dashboard on GitHub Pages.
close #620
---
Check out https://containerd.github.io/runwasi/dev/bench/
=> .github/workflows/benchmarks: support push to Github Pages

Cargo.lock, Cargo.toml
Youki released v0.5 of libcontainer.
This PR moves us back to release versions instead of git dependencies.
=> [chore] revert to versioned release of youki's libcontainer

Cargo.lock, crates/containerd-shim-wasmedge/Cargo.toml, crates/containerd-shim-wasmedge/src/instance.rs, scripts/setup-windows.sh
The corresponding [WasmEdge](https://github.com/WasmEdge/WasmEdge/releases/tag/0.14.1) lib release is 0.14.1.
=> bump wasmedge-sdk from 0.13.2 to 0.14.0

README.md, crates/containerd-shim-wasm/CHANGELOG.md, crates/containerd-shim-wasm/README.md, crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasm/src/sandbox/shim/instance_data.rs, crates/containerd-shim-wasm/src/sandbox/shim/local.rs, crates/containerd-shim-wasm/src/sandbox/shim/local/tests.rs, crates/containerd-shim-wasm/src/sys/unix/container/instance.rs, crates/containerd-shim-wasm/src/sys/windows/container/instance.rs, crates/containerd-shim-wasm/src/testing.rs
This PR removes the `Engine` generic from `InstanceConfig`.
As we move away from reusing one engine for all containers, we don't need to pass the engine around anymore.
This is a breaking change.
=> Remove `Engine` from `InstanceConfig`

.github/workflows/action-test-smoke.yml, scripts/setup-jeager-and-otel.sh, scripts/verify-jaeger-traces.sh
Add a GitHub Action step to verify that Jeager actually receives the expected emitted traces, rather than just hoping they made it.
It uses Jeager API to fetch the traces, and note that the limit=0 so that we can get all the operations.
This is to prevent #787 from happening without getting notices.
=> .github/workflows/action-test-smoke: Add a step to verify the jeager

Cargo.lock, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasm/src/sandbox/cli.rs, crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasm/src/sandbox/oci.rs, crates/containerd-shim-wasm/src/sys/unix/container/instance.rs, crates/containerd-shim-wasm/src/test/signals.rs, crates/containerd-shim-wasm/src/testing.rs
This PR introduces a zygote process (a very small process cloned early on during shim startup), from which new containers are created. This effectively decouples the global state of the shim from the state of the container process.
Fixes #755 and #357
=> Use Zygote process

.github/workflows/benchmarks.yml, crates/containerd-shim-wasm/src/sandbox/cli.rs, scripts/benchmark-mem.sh
This PR adds a memory usage benchmark to CI.
Fixes #802 , at least for the single container use case.
~~The PR is based on #775, I'll rebase once that is merged.~~
~~Marking as draft until then.~~
=> Benchmark memory

.github/workflows/action-test-smoke.yml, crates/containerd-shim-wamr/Cargo.toml, crates/containerd-shim-wasmedge/Cargo.toml, crates/containerd-shim-wasmer/Cargo.toml
Currently, only the wasmtime shim enables the otel tracing. This PR enables the otel tracing for all shims.
=> feat(shims): enable opentelemetry for shims

.github/actions/build/action.yml, .github/actions/setup-env/action.yml, .github/workflows/action-build.yml, .github/workflows/action-check.yml, .github/workflows/action-test-k3s.yml, .github/workflows/action-test-kind.yml, .github/workflows/action-test-smoke.yml, .github/workflows/benchmarks.yml, .github/workflows/ci.yml, .github/workflows/release-wasi-demo-app.yml, .github/workflows/release.yml, Makefile, README.md, benches/containerd-shim-benchmarks/README.md, crates/containerd-shim-wasmtime/README.md, docs/windows-getting-started.md, test/k3s/bootstrap.sh, test/k8s/deploy.oci.yaml, test/k8s/deploy.yaml
- Replaced `make load` with `sudo make pull`
- Updated documents to pull images from `ghcr.io` instead of building them locally
=> feat(*): use published images instead of locally built ones

.github/actions/sign/action.yml, .github/workflows/action-build.yml, Makefile, crates/stress-test/src/mocks/task.rs
This commit adds a stress test to CI with 100 tasks and either # of cores or 10 parallelism
=> feat(ci): add stress test to CI

crates/containerd-shim-wasm/src/sandbox/containerd/client.rs, crates/containerd-shim-wasm/src/sandbox/instance_utils.rs, crates/containerd-shim-wasm/src/sandbox/shim/instance_data.rs, crates/containerd-shim-wasm/src/sandbox/shim/local.rs, crates/containerd-shim-wasm/src/sandbox/shim/otel.rs, crates/containerd-shim-wasm/src/sandbox/shim/task_state.rs, crates/containerd-shim-wasm/src/sys/unix/container/executor.rs, crates/containerd-shim-wasm/src/sys/unix/metrics.rs, crates/containerd-shim-wasmtime/src/instance.rs, scripts/verify-jaeger-traces.sh
this PR converts the TtrpcContext.metadata to the opentelemetry::Context and use it to propogate the parent span information to each TTRPC handler. The result of this change is that we will be able to preserve the context from containerd Task service:
This PR also marks all the utility functions as "Debug" level tracing instead of "Info". The functions that have "Info" tracing are listed below:
1. **Module: `crates/containerd-shim-wasm/src/sandbox/cli.rs`**
- `shim_main_inner`
2. **Module: `crates/containerd-shim-wasm/src/sandbox/instance.rs`**
- `wait`
3. **Module: `crates/containerd-shim-wasm/src/sandbox/shim/cli.rs`**
- `new`
- `start_shim`
- `wait`
- `create_task_service`
- `delete_shim`
4. **Module: `crates/containerd-shim-wasm/src/sandbox/shim/local.rs`**
- `create`
- `start`
- …
=> feat(otel): add context propogation from containerd to the shim

README.md, crates/containerd-shim-wasm/CHANGELOG.md, crates/containerd-shim-wasm/README.md, crates/containerd-shim-wasm/src/container/context.rs, crates/containerd-shim-wasm/src/container/engine.rs, crates/containerd-shim-wasm/src/container/mod.rs, crates/containerd-shim-wasm/src/container/path.rs, crates/containerd-shim-wasm/src/sandbox/cli.rs, crates/containerd-shim-wasm/src/sandbox/instance_utils.rs, crates/containerd-shim-wasm/src/sandbox/mod.rs, crates/containerd-shim-wasm/src/sandbox/sync.rs
Note that breaking change is in this PR that PathResolve is made to be `crate public` instead of `public`.
```
pub(crate) use path::PathResolve;
```
Closes #823
=> docs: improve the docs for containerd-shim-wasm crate

crates/containerd-shim-wasm/CHANGELOG.md, crates/containerd-shim-wasm/src/sys/unix/container/container.rs, crates/containerd-shim-wasm/src/sys/unix/container/instance.rs, crates/containerd-shim-wasm/src/sys/unix/container/mod.rs
This PR creates a dedicated zygote process per container.
This fixes issues with libcontainer changing the shim process global state (like chdir), which leads to race conditions on multithreaded programs.
This also helps with throughput, as the global zygote process was a bottleneck (since it's single threaded).
TODO: Add tests
=> Use a dedicated zygote process per container

.github/workflows/release-wasi-demo-app.yml, Makefile, crates/containerd-shim-wasmtime/README.md
=> change: Rename the image wasi-http to wasi-demo-http

crates/containerd-shim-wasm/src/sandbox/instance.rs
=> fix: Corrected description of containerd_address from GRPC to ttrpc

crates/containerd-shim-wasm/src/sandbox/instance.rs
https://github.com/containerd/runwasi/pull/850#discussion_r1955399701
Revert the merge commit.
However, I will fix the doc comment.
=> Revert "fix: Corrected description of containerd_address from GRPC to ttrpc"

.github/workflows/benchmarks.yml
this is a follow up on #840. It updates the path in the benchmark-http job and adds a timeout for the wait.
=> .github/workflows/benchmarks: fix the image path

crates/containerd-shim-wasm/src/sandbox/cli.rs, crates/containerd-shim-wasm/src/sandbox/containerd/client.rs, crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasm/src/sandbox/instance_utils.rs, crates/containerd-shim-wasm/src/sandbox/shim/cli.rs, crates/containerd-shim-wasm/src/sandbox/shim/instance_data.rs, crates/containerd-shim-wasm/src/sandbox/shim/local.rs, crates/containerd-shim-wasm/src/sandbox/shim/task_state.rs, crates/containerd-shim-wasm/src/sys/unix/container/executor.rs, crates/containerd-shim-wasm/src/sys/unix/container/instance.rs, crates/containerd-shim-wasm/src/sys/unix/metrics.rs, crates/containerd-shim-wasmtime/src/instance.rs
this commit also removes 'parent = ...' since it's already in the default
---
Notice how `version`, `revision`, and `name` are now included in the tags.
=> tracing: add parameters info to the trace instead of skipping them

Cargo.lock, crates/stress-test/Cargo.toml, crates/stress-test/protos/github.com/containerd/containerd/api/runtime/task/v3/shim.proto, crates/stress-test/src/containerd/client.rs, crates/stress-test/src/containerd/containerd.rs, crates/stress-test/src/containerd/task.rs, crates/stress-test/src/main.rs, crates/stress-test/src/mocks/containerd.rs, crates/stress-test/src/mocks/mod.rs, crates/stress-test/src/mocks/shim.rs, crates/stress-test/src/mocks/task.rs, crates/stress-test/src/mocks/task_client.rs, crates/stress-test/src/protos.rs, crates/stress-test/src/traits.rs
With this change it is now possible to do something like:
```
sudo ctr images pull ghcr.io/jprendes/wasmtime-distroless/hello:latest
cargo run -p stress-test -- /usr/bin/containerd-shim-runc-v2 --image ghcr.io/jprendes/wasmtime-distroless/hello:latest
```
=> [stress-test] Add support for native containers

.github/workflows/benchmarks.yml, Makefile, crates/stress-test/src/main.rs
In addition, this commit adds a release flag to stress test CLI in Makefile.
=> ci: Add oci and oci-artifact images to stress test

crates/stress-test/src/containerd/client.rs, crates/stress-test/src/main.rs, crates/stress-test/src/mocks/shim.rs
Currently CI is broken, this PR tries to fix that.
=> [stress-test] add default arguments for OCI image

crates/containerd-shim-wasm/src/sys/unix/container/instance.rs, crates/containerd-shim-wasm/src/sys/unix/mod.rs, crates/containerd-shim-wasm/src/sys/unix/pid_fd.rs, crates/stress-test/src/containerd/client.rs, crates/stress-test/src/main.rs, crates/stress-test/src/mocks/shim.rs
This PR replaces the blocking waitid call with an async implementation based on pid fd.
There's a race condition where containerd-shim reaps child processes.
If the child process has already been reaped, query containerd-shim to get the process status.
Note that this race condition is already present in the current implementation, but runwasi's waitid is very likely to win the race, the introduction of async evens out the odds between runwasi and containerd-shim.
This PR is in preparation to move the whole shim implementation to async.
=> Use async pid fd instead of blocking waitid to wait for a child process to exit

crates/containerd-shim-wasm/CHANGELOG.md, crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasm/src/sandbox/shim/instance_data.rs, crates/containerd-shim-wasm/src/sandbox/shim/local.rs, crates/containerd-shim-wasm/src/sys/unix/container/instance.rs, crates/containerd-shim-wasm/src/testing.rs
As in the title.
This PR removes some accessor methods that aren't very rusty, and replaces it with `pub` struct members instead.
=> [chore] Remove some redundant accessor methods

README.md, crates/containerd-shim-wasm/README.md, crates/containerd-shim-wasm/src/sandbox/async_utils.rs, crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasm/src/sandbox/mod.rs, crates/containerd-shim-wasm/src/sandbox/shim/instance_data.rs, crates/containerd-shim-wasm/src/sandbox/shim/local.rs, crates/containerd-shim-wasm/src/sandbox/shim/local/tests.rs, crates/containerd-shim-wasm/src/sandbox/sync.rs, crates/containerd-shim-wasm/src/sys/unix/container/instance.rs, crates/containerd-shim-wasm/src/sys/windows/container/instance.rs, crates/containerd-shim-wasm/src/testing.rs
This PR changes the `Instance`'s wait method to be async.
This is a step towards migrating to an async shim.
This has the nice benefit that we get sync probing (`try_wait`) and timed wait (`wait_timeout`) for free.
We get probing through `FutureExt::now_or_never`, and timed wait through `tokio::time::timeout`.
This also simplifies the implementation of `WaitableCell` a fair bit.
=> Use async for the instance's wait method

Makefile
Recently the k3s e2e tests have started failing with
```
Events:
Type     Reason                  Age                  From               Message
----     ------                  ----                 ----               -------
Normal   Scheduled               5m                   default-scheduler  Successfully assigned default/wasi-demo-77898cb6bf-bmkrm to fv-az1207-240
Warning  FailedCreatePodSandBox  5m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = unable to get OCI runtime for sandbox "2c50cc6abfb505d18e8a7e8e5c865c5941646d1b36b565428e2e583bba01baaa": no runtime for "wasm" is configured
Warning  FailedCreatePodSandBox  4m46s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = unable to …
```
=> [CI] pin the k3s version

README.md, crates/containerd-shim-wasm/README.md, crates/containerd-shim-wasm/src/sandbox/cli.rs, crates/containerd-shim-wasm/src/sandbox/instance.rs, crates/containerd-shim-wasm/src/sandbox/mod.rs, crates/containerd-shim-wasm/src/sandbox/shim/cli.rs, crates/containerd-shim-wasm/src/sandbox/shim/local.rs, crates/containerd-shim-wasm/src/sandbox/shim/local/tests.rs, crates/containerd-shim-wasm/src/sys/unix/container/instance.rs, crates/containerd-shim-wasm/src/sys/windows/container/instance.rs, crates/containerd-shim-wasm/src/testing.rs
There's an unused engine field in the `Local` struct that somehow was not being flagged as unused.
This PR removes that field, and related now redundant types.
=> [chore] Remove unused engine field

crates/containerd-shim-wamr/Cargo.toml, crates/containerd-shim-wamr/src/instance.rs, crates/containerd-shim-wasm/CHANGELOG.md, crates/containerd-shim-wasm/src/container/context.rs, crates/containerd-shim-wasm/src/container/log.rs, crates/containerd-shim-wasm/src/container/mod.rs, crates/containerd-shim-wasm/src/sys/unix/container/executor.rs, crates/containerd-shim-wasm/src/sys/unix/container/instance.rs, crates/containerd-shim-wasmedge/Cargo.toml, crates/containerd-shim-wasmedge/src/instance.rs, crates/containerd-shim-wasmer/Cargo.toml, crates/containerd-shim-wasmer/src/instance.rs, crates/containerd-shim-wasmtime/src/http_proxy.rs, crates/containerd-shim-wasmtime/src/instance.rs
- **containerd-shim-wasm/src/sandbox/cli: add logger to the container process**
- **feat(all): add container id to runtimeContext so that logs can refer to it**
The purpose of adding `id` to RuntimeContext is that containers can add the id to their log messages to differentiate from other containers in the same pod. 
The disadvantage of this method is that functions that do not import `ctx: RuntimeContext` will not be able to have the container id in their logs.
This builds on top of #878 
---
The following is containerd log for a pod that has three wasm tasks. 
```console
time="2025-02-25T22:12:39.421124341Z" level=info instance="7e7916133550e01b22c57fbcb85ae0b18282a28dac7a61da18d0ebc52f5cc43c" msg="setting up wasi"
time="2025-02-25T22:12:39.918793845Z" level=info …
```
=> add container ID and pod ID to RuntimeContext and logs

.github/workflows/scorecard-analysis.yml
OSSF scorecard is a tool that analyzes the security of a project.
This commit adds a GH Action workflow to run weekly, generating a scorecard in the form of SARIF report and uploading it to the GitHub's code scanning dashboard.
=> ci: Add GitHub Actions workflow for scorecard analysis

Cargo.lock
this is a recommended upgrade by the https://rustsec.org/advisories/RUSTSEC-2024-0421.html
=> chore(deps): update url to 2.5.4 which bumps idna to 1.0.3

Cargo.lock
This is a recommended upgrade by the https://rustsec.org/advisories/RUSTSEC-2025-0004
=> chore(deps): Bumped openssl from 0.10.68 to 0.10.70

.github/workflows/action-build.yml, .github/workflows/action-check.yml, .github/workflows/action-test-image.yml, .github/workflows/action-test-k3s.yml, .github/workflows/action-test-kind.yml, .github/workflows/action-test-smoke.yml, .github/workflows/benchmarks.yml, .github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/release-wasi-demo-app.yml, .github/workflows/release.yml, .github/workflows/sbom.yml, .github/workflows/sign.yml
By explicitly adding the read-all permission to all workflows, we can
reduce the number of false positives in the scorecard check.
E.g. https://github.com/containerd/runwasi/security/code-scanning/21
=> ci(all): add read-all permission to all workflows

test/k3s/bootstrap.sh, test/k8s/Dockerfile
Taking over this PR: https://github.com/containerd/runwasi/pull/875
=> Add systemd cgroup support for k3s and k8s

crates/containerd-shim-wasm/CHANGELOG.md, crates/containerd-shim-wasm/src/container/mod.rs, crates/containerd-shim-wasm/src/sandbox/cli.rs, crates/containerd-shim-wasm/src/sandbox/mod.rs, crates/containerd-shim-wasm/src/sandbox/shim/mod.rs, crates/containerd-shim-wasm/src/sandbox/shim/shim.rs, scripts/verify-jaeger-traces.sh
in addition, added detailed documentation for key components and example usage in the `container` module.
=> breaking: `shim::cli` is now crate public

crates/containerd-shim-wasm/src/container/context.rs, crates/containerd-shim-wasm/src/container/path.rs
=> containerd-shim-wasm/src/container: updated comments to doc comments for RuntimeContext and PathResolve traits.

Cargo.lock, Cargo.toml, crates/containerd-shim-wasmedge/Cargo.toml, crates/containerd-shim-wasmedge/src/instance.rs
As title.
I have prepared a verification repo demonstrating how to use the wasi_nn plugin with ggml backend.
https://github.com/CaptainVincent/runwasi-wasmedge-demo
And a CI workflow testing in [here](https://github.com/CaptainVincent/runwasi-wasmedge-demo/actions).
=> Add plugin support to WasmEdge runtime

Cargo.lock, crates/containerd-shim-wamr/src/instance.rs, crates/containerd-shim-wasm/CHANGELOG.md, crates/containerd-shim-wasm/Cargo.toml, crates/containerd-shim-wasm/README.md, crates/containerd-shim-wasm/src/container/context.rs, crates/containerd-shim-wasm/src/container/engine.rs, crates/containerd-shim-wasm/src/container/mod.rs, crates/containerd-shim-wasm/src/container/tests.rs, crates/containerd-shim-wasm/src/sandbox/cli.rs, crates/containerd-shim-wasm/src/sandbox/containerd/client.rs, crates/containerd-shim-wasm/src/sys/unix/container/executor.rs, crates/containerd-shim-wasm/src/test/signals.rs, crates/containerd-shim-wasmedge/src/instance.rs, crates/containerd-shim-wasmer/src/instance.rs, crates/containerd-shim-wasmtime/src/instance.rs
This PR makes most of the methods in the `Engine` trait `async`.
The `name` and `supported_layers_types` methods are left as non-async methods, as they are intended more as configuration than for doing any actual computation.
=> make the engine trait async

crates/containerd-shim-wamr/src/instance.rs, crates/containerd-shim-wamr/src/main.rs, crates/containerd-shim-wasm/README.md, crates/containerd-shim-wasm/src/lib.rs, crates/containerd-shim-wasm/src/sandbox/cli.rs, crates/containerd-shim-wasm/src/shim/mod.rs, crates/containerd-shim-wasm/src/shim/shim.rs, crates/containerd-shim-wasmedge/src/instance.rs, crates/containerd-shim-wasmedge/src/main.rs, crates/containerd-shim-wasmer/src/instance.rs, crates/containerd-shim-wasmer/src/main.rs, crates/containerd-shim-wasmtime/src/instance.rs, crates/containerd-shim-wasmtime/src/main.rs, crates/containerd-shimkit/src/sandbox/cli.rs
This PR removes the `shim_main` free function and replaces it with a `ShimCli::run` trait method.
This trait is implemented for all Shim traits.
It also adds a new `fn version() -> Version` method to engine, and the corresponding `Version` struct.
=> Move `shim_main` from free function to method in a trait

.github/workflows/release.yml, RELEASE.md
=> release: skip the ownership step if the crate is the initial release

.github/workflows/release.yml
the issue with adding runwasi committers as an owner is that the release bot does not have the visibility to see it.
=> .github/workflows/release: Update crates.io ownership check to use GH actor instead of runwasi committers

.github/workflows/ci.yml
**Solves:** [https://github.com/containerd/runwasi/issues/995](https://github.com/containerd/runwasi/issues/995)
Ubuntu 20.04 LTS has reached EOL and has been removed from GitHub-hosted runners. runwasi ci initially used it to test cgroups v1, but after reviewing all currently supported GitHub-hosted Linux runners, none appear to support cgroups v1 by default.
Given this, I've removed the Ubuntu 20.04 runner and the corresponding cgroups v1 test.
Let me know if you'd like any adjustments. Happy to help!
=> Remove cgroup v1 and Ubuntu 20.04 tests from CI workflow

Cargo.lock, Cargo.toml, crates/containerd-shim-wasmtime/src/http_proxy.rs, crates/containerd-shim-wasmtime/src/instance.rs
- `IOView` is split off of `WasiView`. https://github.com/bytecodealliance/wasmtime/pull/10016
- `static_memory_maximum_size` is now `memory_reservation`. https://github.com/bytecodealliance/wasmtime/pull/9545
- `detect_precompiled` is now associated function. https://github.com/bytecodealliance/wasmtime/pull/10405
- Moved WASIp2 related things to `wasmtime_wasi::p2` module. https://github.com/bytecodealliance/wasmtime/pull/10073
=> deps: bump wasmtime to 33.0.0
